/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.clothingsystemruntimecommon;

/**
  Deprecated, legacy definition kept for backward compatibility only.
  Use EClothingWindMethodNv instead.
  Redirected from the now defunct ClothingSystemRuntime module.
**/
@:umodule("ClothingSystemRuntimeCommon")
@:glueCppIncludes("Public/ClothConfig_Legacy.h")
@:uname("EClothingWindMethod_Legacy")
@:class @:uextern @:uenum extern enum EClothingWindMethod_Legacy {
  
  /**
    Use legacy wind mode, where accelerations are modified directly by the simulation
    with no regard for drag or lift
  **/
  Legacy;
  
  /**
    Use updated wind calculation for NvCloth based solved taking into account
    drag and lift, this will require those properties to be correctly set in
    the clothing configuration
  **/
  Accurate;
  
}
