/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescenetracks;

/**
  Struct to hold the cached root motion positions based upon how we calculated them.
  Also provides way to get the root motion at a particular time.
**/
@:umodule("MovieSceneTracks")
@:glueCppIncludes("Public/Tracks/MovieSceneSkeletalAnimationTrack.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMovieSceneSkeletalAnimRootMotionTrackParams {
  
}
