/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescenetracks;

/**
  Template that performs evaluation of parameter sections
**/
@:umodule("MovieSceneTracks")
@:glueCppIncludes("Public/Evaluation/MovieSceneParameterTemplate.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMovieSceneParameterSectionTemplate extends unreal.moviescene.FMovieSceneEvalTemplate {
  @:uproperty private var Transforms : unreal.TArray<unreal.moviescenetracks.FTransformParameterNameAndCurves>;
  
  /**
    The color parameter names and their associated curves.
  **/
  @:uproperty private var Colors : unreal.TArray<unreal.moviescenetracks.FColorParameterNameAndCurves>;
  
  /**
    The vector parameter names and their associated curves.
  **/
  @:uproperty private var Vectors : unreal.TArray<unreal.moviescenetracks.FVectorParameterNameAndCurves>;
  
  /**
    The vector parameter names and their associated curves.
  **/
  @:uproperty private var Vector2Ds : unreal.TArray<unreal.moviescenetracks.FVector2DParameterNameAndCurves>;
  
  /**
    The bool parameter names and their associated curves.
  **/
  @:uproperty private var Bools : unreal.TArray<unreal.moviescenetracks.FBoolParameterNameAndCurve>;
  
  /**
    The scalar parameter names and their associated curves.
  **/
  @:uproperty private var Scalars : unreal.TArray<unreal.moviescenetracks.FScalarParameterNameAndCurve>;
  
}
