/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.oculushmd;

@:umodule("OculusHMD")
@:glueCppIncludes("Public/OculusFunctionLibrary.h")
@:uname("EFixedFoveatedRenderingLevel")
@:class @:uextern @:uenum extern enum EFixedFoveatedRenderingLevel {
  FFR_Off;
  FFR_Low;
  FFR_Medium;
  FFR_High;
  
  /**
    High foveation setting with more detail toward the bottom of the view and more foveation near the top
  **/
  FFR_HighTop;
  
}
