/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.takemoviescene;

/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  Universal take recorder settings that apply to a whole take
**/
@:umodule("TakeMovieScene")
@:glueCppIncludes("MovieSceneTakeSettings.h")
@:uextern @:uclass extern class UMovieSceneTakeSettings extends unreal.UObject {
  
  /**
    Slate Name
  **/
  @:uproperty public var SlateName : unreal.FString;
  
  /**
    SubFrames Name
  **/
  @:uproperty public var SubFramesName : unreal.FString;
  
  /**
    Frames Name
  **/
  @:uproperty public var FramesName : unreal.FString;
  
  /**
    Seconds Name
  **/
  @:uproperty public var SecondsName : unreal.FString;
  
  /**
    Minutes Name
  **/
  @:uproperty public var MinutesName : unreal.FString;
  
  /**
    Hours Name
  **/
  @:uproperty public var HoursName : unreal.FString;
  
}
