/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.livelinkmoviescene;

@:umodule("LiveLinkMovieScene")
@:glueCppIncludes("Public/MovieScene/MovieSceneLiveLinkStructProperties.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FLiveLinkPropertyData {
  @:uproperty public var ByteChannel : unreal.TArray<unreal.moviescene.FMovieSceneByteChannel>;
  @:uproperty public var BoolChannel : unreal.TArray<unreal.moviescene.FMovieSceneBoolChannel>;
  @:uproperty public var IntegerChannel : unreal.TArray<unreal.moviescene.FMovieSceneIntegerChannel>;
  @:uproperty public var StringChannel : unreal.TArray<unreal.moviescenetracks.FMovieSceneStringChannel>;
  @:uproperty public var FloatChannel : unreal.TArray<unreal.moviescene.FMovieSceneFloatChannel>;
  @:uproperty public var PropertyName : unreal.FName;
  
}
