/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraDataInterfaceStaticMesh.h")
@:uname("ENDIStaticMesh_SourceMode")
@:class @:uextern @:uenum extern enum ENDIStaticMesh_SourceMode {
  
  /**
    Default behavior.
    - Use "Source" when specified (either set explicitly or via blueprint with Set Niagara Static Mesh Component).
    - When no source is specified, attempt to find a Static Mesh Component on an attached actor or component.
    - If no source actor/component specified and no attached component found, fall back to the "Default Mesh" specified.
  **/
  Default;
  
  /**
    Only use "Source" (either set explicitly or via blueprint with Set Niagara Static Mesh Component).
  **/
  Source;
  
  /**
    Only use the parent actor or component the system is attached to.
  **/
  AttachParent;
  
  /**
    Only use the "Default Mesh" specified.
  **/
  DefaultMeshOnly;
  
}
