/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraScript.h")
@:uname("ENiagaraScriptLibraryVisibility")
@:class @:uextern @:uenum extern enum ENiagaraScriptLibraryVisibility {
  Invalid;
  
  /**
    The script is not visible by default to the user, but can be made visible by disabling the "Library only" filter option.
    @DisplayName Unexposed
  **/
  @DisplayName("Unexposed")
  Unexposed;
  
  /**
    The script is exposed to the asset library and always visible to the user.
    @DisplayName Exposed
  **/
  @DisplayName("Exposed")
  Library;
  
  /**
    The script is never visible to the user. This is useful to "soft deprecate" assets that should not be shown to a user, but should also not generate errors for existing usages.
    @DisplayName Hidden
  **/
  @DisplayName("Hidden")
  Hidden;
  
}
