/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("Public/NiagaraMeshRendererProperties.h")
@:uextern @:ustruct extern class FNiagaraMeshRendererMeshProperties {
  
  /**
    What space is the pivot offset in?
  **/
  @:uproperty public var PivotOffsetSpace : unreal.niagara.ENiagaraMeshPivotOffsetSpace;
  
  /**
    Offset of the mesh pivot
  **/
  @:uproperty public var PivotOffset : unreal.FVector;
  
  /**
    Scale of the mesh
  **/
  @:uproperty public var Scale : unreal.FVector;
  
  /**
    The mesh to use when rendering this slot
  **/
  @:uproperty public var Mesh : unreal.UStaticMesh;
  
}
