/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

/**
  Helper class defining the layout and location of an FNiagaraVariable in an FNiagaraDataBuffer->
**/
@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraDataSet.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FNiagaraVariableLayoutInfo {
  
  /**
    This variable's type layout info.
  **/
  @:uproperty public var LayoutInfo : unreal.niagara.FNiagaraTypeLayoutInfo;
  
  /**
    Start index for the half components in the main buffer.
  **/
  @:uproperty public var HalfComponentStart : unreal.FakeUInt32;
  
  /**
    Start index for the int32 components in the main buffer.
  **/
  @:uproperty public var Int32ComponentStart : unreal.FakeUInt32;
  
  /**
    Start index for the float components in the main buffer.
  **/
  @:uproperty public var FloatComponentStart : unreal.FakeUInt32;
  
}
