/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.materialeditor;

@:umodule("MaterialEditor")
@:glueCppIncludes("Public/MaterialEditingLibrary.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMaterialStatistics {
  
  /**
    Number of interpolator scalars required for user-defined interpolators
  **/
  @:uproperty public var NumInterpolatorScalars : unreal.Int32;
  
  /**
    Number of interpolator scalars required for UVs
  **/
  @:uproperty public var NumUVScalars : unreal.Int32;
  
  /**
    Number of virtual textures sampled
  **/
  @:uproperty public var NumVirtualTextureSamples : unreal.Int32;
  
  /**
    Number of textures sampled by the pixel shader
  **/
  @:uproperty public var NumPixelTextureSamples : unreal.Int32;
  
  /**
    Number of textures sampled by the vertex shader
  **/
  @:uproperty public var NumVertexTextureSamples : unreal.Int32;
  
  /**
    Number of samplers required by the material
  **/
  @:uproperty public var NumSamplers : unreal.Int32;
  
  /**
    Number of instructions used by most expensive pixel shader in the material
  **/
  @:uproperty public var NumPixelShaderInstructions : unreal.Int32;
  
  /**
    Number of instructions used by most expensive vertex shader in the material
  **/
  @:uproperty public var NumVertexShaderInstructions : unreal.Int32;
  
}
