/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraDataInterfaceSkeletalMesh.h")
@:uname("ENDISkeletalMesh_SourceMode")
@:class @:uextern @:uenum extern enum ENDISkeletalMesh_SourceMode {
  
  /**
    Default behavior.
    - Use "Source" when specified (either set explicitly or via blueprint with Set Niagara Skeletal Mesh Component).
    - When no source is specified, fall back on attached actor or component.
  **/
  Default;
  
  /**
    Only use "Source" (either set explicitly or via blueprint with Set Niagara Skeletal Mesh Component).
  **/
  Source;
  
  /**
    Only use the parent actor or component the system is attached to.
  **/
  AttachParent;
  
}
