/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

/**
  Defines different usages for a niagara script.
**/
@:umodule("Niagara")
@:glueCppIncludes("Public/NiagaraCommon.h")
@:uname("ENiagaraCompileUsageStaticSwitch")
@:class @:uextern @:uenum extern enum ENiagaraCompileUsageStaticSwitch {
  
  /**
    The script is called during the spawn phase.
  **/
  Spawn;
  
  /**
    The script is called during the update phase.
  **/
  Update;
  
  /**
    The script is called in an event context.
  **/
  Event;
  
  /**
    The script is called as part of a simulation stage.
  **/
  SimulationStage;
  
  /**
    The default value if the compiler cannot map the compilation context.
  **/
  Default;
  
}
