/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

/**
  Controls how often should we update scalability states for these effects.
**/
@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraEffectType.h")
@:uname("ENiagaraScalabilityUpdateFrequency")
@:class @:uextern @:uenum extern enum ENiagaraScalabilityUpdateFrequency {
  
  /**
    Scalability will be checked only on spawn.
  **/
  SpawnOnly;
  
  /**
    Scalability will be checked infrequently.
  **/
  Low;
  
  /**
    Scalability will be occasionally.
  **/
  Medium;
  
  /**
    Scalability will be checked regularly.
  **/
  High;
  
  /**
    Scalability will be checked every frame.
  **/
  Continuous;
  
}
