/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("Public/NiagaraRibbonRendererProperties.h")
@:uname("ENiagaraRibbonShapeMode")
@:class @:uextern @:uenum extern enum ENiagaraRibbonShapeMode {
  
  /**
    Default shape, flat plane facing the camera.
  **/
  Plane;
  
  /**
    Multiple Planes evenly rotated around the axis to 180 degrees.
  **/
  MultiPlane;
  
  /**
    3D Tube shape, from triangular to cylindrical depending on vertex count.
  **/
  Tube;
  
  /**
    Custom shape, defined by cross section.
  **/
  Custom;
  
}
