/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraPlatformSet.h")
@:uextern @:ustruct extern class FNiagaraPlatformSet {
  
  /**
    Set of CVars values we require for this platform set to be enabled. If any of the linked CVars don't have the required values then this platform set will not be enabled.
  **/
  @:uproperty public var CVarConditions : unreal.TArray<unreal.niagara.FNiagaraPlatformSetCVarCondition>;
  
  /**
    States of specific device profiles we've set.
  **/
  @:uproperty public var DeviceProfileStates : unreal.TArray<unreal.niagara.FNiagaraDeviceProfileStateEntry>;
  
  /**
    Mask defining which effects qualities this set matches.
  **/
  @:uproperty public var QualityLevelMask : unreal.Int32;
  
}
