/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

/**
  Information about how this type should be laid out in an FNiagaraDataSet
**/
@:umodule("Niagara")
@:glueCppIncludes("Public/NiagaraTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FNiagaraTypeLayoutInfo {
  
  /**
    Offset into register table for each half component.
  **/
  @:uproperty public var HalfComponentRegisterOffsets : unreal.TArray<unreal.FakeUInt32>;
  
  /**
    Byte offset of each half component in a structured layout.
  **/
  @:uproperty public var HalfComponentByteOffsets : unreal.TArray<unreal.FakeUInt32>;
  
  /**
    Offset into register table for each int32 component.
  **/
  @:uproperty public var Int32ComponentRegisterOffsets : unreal.TArray<unreal.FakeUInt32>;
  
  /**
    Byte offset of each int32 component in a structured layout.
  **/
  @:uproperty public var Int32ComponentByteOffsets : unreal.TArray<unreal.FakeUInt32>;
  
  /**
    Offset into register table for each float component.
  **/
  @:uproperty public var FloatComponentRegisterOffsets : unreal.TArray<unreal.FakeUInt32>;
  
  /**
    Byte offset of each float component in a structured layout.
  **/
  @:uproperty public var FloatComponentByteOffsets : unreal.TArray<unreal.FakeUInt32>;
  
}
