/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

/**
  Scalability settings for Niagara Systems for a particular platform set (unless overridden).
**/
@:umodule("Niagara")
@:glueCppIncludes("Classes/NiagaraEffectType.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FNiagaraSystemScalabilitySettings {
  
  /**
    Effects will be culled if the global budget usage exceeds this fraction. A global budget usage of 1.0 means current global FX workload has reached it's max budget. Budgets are set by CVars under FX.Budget...
  **/
  @:uproperty public var MaxGlobalBudgetUsage : unreal.Float32;
  
  /**
    Effects will be culled if they go more than this length of time without being rendered.
  **/
  @:uproperty public var MaxTimeWithoutRender : unreal.Float32;
  
  /**
    Effects of this type will be culled when total active instances of the same NiagaraSystem exceeds this number.
    If the effect type has a significance handler, instances are sorted by their significance and only the N most significant will be kept. The rest are culled.
    If it does not have a significance handler, instance count culling will be applied at spawn time only. New FX that would exceed the counts are not spawned/activated.
  **/
  @:uproperty public var MaxSystemInstances : unreal.Int32;
  
  /**
    Effects of this type will be culled when total active instances using this same EffectType exceeds this number.
    If the effect type has a significance handler, instances are sorted by their significance and only the N most significant will be kept. The rest are culled.
    If it does not have a significance handler, instance count culling will be applied at spawn time only. New FX that would exceed the counts are not spawned/activated.
  **/
  @:uproperty public var MaxInstances : unreal.Int32;
  
  /**
    Effects of this type are culled beyond this distance.
  **/
  @:uproperty public var MaxDistance : unreal.Float32;
  
  /**
    Controls whether global budget based culling is enabled.
  **/
  @:uproperty public var bCullByGlobalBudget : Bool;
  
  /**
    Controls whether visibility culling is enabled.
  **/
  @:uproperty public var bCullByMaxTimeWithoutRender : Bool;
  
  /**
    Controls whether we should cull systems based on how many instances of the system are active.
  **/
  @:uproperty public var bCullPerSystemMaxInstanceCount : Bool;
  
  /**
    Controls whether we should cull systems based on how many instances with the same Effect Type are active.
  **/
  @:uproperty public var bCullMaxInstanceCount : Bool;
  
  /**
    Controls whether distance culling is enabled.
  **/
  @:uproperty public var bCullByDistance : Bool;
  
  /**
    The platforms on which these settings are active (unless overridden).
  **/
  @:uproperty public var Platforms : unreal.niagara.FNiagaraPlatformSet;
  
}
