/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("NiagaraDataInterfaceCamera.h")
@:uextern @:uclass extern class UNiagaraDataInterfaceCamera extends unreal.niagara.UNiagaraDataInterface {
  
  /**
    When this option is disabled, we use the previous frame's data for the camera and issue the simulation early. This greatly
          reduces overhead and allows the game thread to run faster, but comes at a tradeoff if the dependencies might leave gaps or other visual artifacts.
  **/
  @:uproperty public var bRequireCurrentFrameData : Bool;
  
  /**
    This is used to determine which camera position to query for cpu emitters. If no valid index is supplied, the first controller is used as camera reference.
  **/
  @:uproperty public var PlayerControllerIndex : unreal.Int32;
  
}
