/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("NiagaraSettings.h")
@:uextern @:uclass extern class UNiagaraSettings extends unreal.developersettings.UDeveloperSettings {
  
  /**
    Controls the format used for specifying triangle indexes in adjacency buffers.  Changing this setting requires restarting the editor.
  **/
  @:uproperty public var NDISkelMesh_AdjacencyTriangleIndexFormat : unreal.niagara.ENDISkelMesh_AdjacencyTriangleIndexFormat;
  
  /**
    Controls the format used for uniform sampling on the GPU.  Changing this setting requires restarting the editor.
  **/
  @:uproperty public var NDISkelMesh_GpuUniformSamplingFormat : unreal.niagara.ENDISkelMesh_GpuUniformSamplingFormat;
  
  /**
    Controls the maximum number of influences we allow the Skeletal Mesh Data Interface to use on the GPU.  Changing this setting requires restarting the editor.
  **/
  @:uproperty public var NDISkelMesh_GpuMaxInfluences : unreal.niagara.ENDISkelMesh_GpuMaxInfluences;
  
  /**
    The default setting for motion vectors in Niagara renderers
  **/
  @:uproperty public var DefaultRendererMotionVectorSetting : unreal.niagara.ENiagaraDefaultRendererMotionVectorSetting;
  
  /**
    The default buffer format used by all Niagara Grid Data Interfaces unless overridden.
  **/
  @:uproperty public var DefaultGridFormat : unreal.niagara.ENiagaraGpuBufferFormat;
  
  /**
    The default render target format used by all Niagara Render Target Data Interfaces unless overridden.
  **/
  @:uproperty public var DefaultRenderTargetFormat : unreal.ETextureRenderTargetFormat;
  
  /**
    Info texts that the component renderer shows the user depending on the selected component class.
  **/
  @:uproperty public var ComponentRendererWarningsPerClass : unreal.TMap<unreal.FString, unreal.FText>;
  
  /**
    The quality levels Niagara uses.
  **/
  @:uproperty public var QualityLevels : unreal.TArray<unreal.FText>;
  
  /**
    Default effect type to use for effects that don't define their own. Can be null.
  **/
  @:uproperty public var DefaultEffectType : unreal.FSoftObjectPath;
  #if WITH_EDITORONLY_DATA
  
  /**
    Sets the default navigation behavior for the system preview viewport.
  **/
  @:uproperty public var bSystemViewportInOrbitMode : Bool;
  @:uproperty public var AdditionalParameterEnums : unreal.TArray<unreal.FSoftObjectPath>;
  @:uproperty public var AdditionalPayloadTypes : unreal.TArray<unreal.FSoftObjectPath>;
  @:uproperty public var AdditionalParameterTypes : unreal.TArray<unreal.FSoftObjectPath>;
  #end // WITH_EDITORONLY_DATA
  
}
