/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagara;

@:umodule("Niagara")
@:glueCppIncludes("NiagaraSimulationStageBase.h")
@:uextern @:uclass extern class UNiagaraSimulationStageGeneric extends unreal.niagara.UNiagaraSimulationStageBase {
  
  /**
    Source data interface to use for the simulation stage. The data interface needs to be a subclass of UNiagaraDataInterfaceRWBase, for example the Grid2D and Grid3D data interfaces.
  **/
  @:uproperty public var DataInterface : unreal.niagara.FNiagaraVariableDataInterfaceBinding;
  
  /**
    Disables the ability to read / write from the same particle buffer, i.e. only update position and no other attributes.  By default this should not be changed and is a debugging tool.
  **/
  @:uproperty public var bDisablePartialParticleUpdate : Bool;
  
  /**
    When enabled the stage will only run on the first tick after the emitter is reset, only valid for data interface iteration stages
  **/
  @:uproperty public var bSpawnOnly : Bool;
  
  /**
    The number of times we run this simulation stage before moving to the next stage.
  **/
  @:uproperty public var Iterations : unreal.Int32;
  
  /**
    Determine which elements this script is iterating over. You are not allowed to
  **/
  @:uproperty public var IterationSource : unreal.niagara.ENiagaraIterationSource;
  
}
