/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.meshpaintingtoolset;

@:umodule("MeshPaintingToolset")
@:glueCppIncludes("MeshVertexPaintingTool.h")
@:uextern @:uclass extern class UMeshWeightPaintingToolProperties extends unreal.meshpaintingtoolset.UMeshVertexPaintingToolProperties {
  
  /**
    Texture Blend Weight index which should be erased during Painting
  **/
  @:uproperty public var EraseTextureWeightIndex : unreal.meshpaintingtoolset.EMeshPaintTextureIndex;
  
  /**
    Texture Blend Weight index which should be applied during Painting
  **/
  @:uproperty public var PaintTextureWeightIndex : unreal.meshpaintingtoolset.EMeshPaintTextureIndex;
  
  /**
    Texture Blend Weight Painting Mode
  **/
  @:uproperty public var TextureWeightType : unreal.meshpaintingtoolset.EMeshPaintWeightTypes;
  
}
