/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  An enumeration for specifying quantization boundary reference frame
**/
@:glueCppIncludes("Classes/Sound/QuartzQuantizationUtilities.h")
@:uname("EQuarztQuantizationReference")
@:class @:uextern @:uenum extern enum EQuarztQuantizationReference {
  
  /**
    Will occur on the next occurence of this duration from the start of a bar (i.e. On beat 3)
    @DisplayName Bar Relative
  **/
  @DisplayName("Bar Relative")
  BarRelative;
  
  /**
    Will occur on the next multiple of this duration since the clock started ticking (i.e. on the next 4 bar boundary)
    @DisplayName Transport Relative
  **/
  @DisplayName("Transport Relative")
  TransportRelative;
  
  /**
    Will occur on the next multiple of this duration from the current time (i.e. In three beats)
    @DisplayName Current Time Relative
  **/
  @DisplayName("Current Time Relative")
  CurrentTimeRelative;
  Count;
  
}
