/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Engine/SkeletalMesh.h")
@:uname("ESkinCacheDefaultBehavior")
@:class @:uextern @:uenum extern enum ESkinCacheDefaultBehavior {
  
  /**
    All skeletal meshes are excluded from the skin cache. Each must opt in individually. If Ray Tracing is enabled, will imply Inclusive
  **/
  Exclusive;
  
  /**
    All skeletal meshes are included into the skin cache. Each must opt out individually
  **/
  Inclusive;
  
}
