/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Engine/TextureDefines.h")
@:uname("ETextureLossyCompressionAmount")
@:uextern @:uenum extern enum ETextureLossyCompressionAmount {
  
  /**
    Default
  **/
  @DisplayName("Default")
  TLCA_Default;
  
  /**
    No lossy compression
  **/
  @DisplayName("No lossy compression")
  TLCA_None;
  
  /**
    Lowest (Best image quality, largest filesize)
  **/
  @DisplayName("Lowest (Best image quality, largest filesize)")
  TLCA_Lowest;
  
  /**
    Low
  **/
  @DisplayName("Low")
  TLCA_Low;
  
  /**
    Medium
  **/
  @DisplayName("Medium")
  TLCA_Medium;
  
  /**
    High
  **/
  @DisplayName("High")
  TLCA_High;
  
  /**
    Highest (Worst image quality, smallest filesize)
  **/
  @DisplayName("Highest (Worst image quality, smallest filesize)")
  TLCA_Highest;
  
}
