/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Intermediate data stream used for network serialization of Character RPC data.
  This is basically an array of bits that is packed/unpacked via NetSerialize into custom data structs on the sending and receiving ends.
**/
@:glueCppIncludes("Classes/GameFramework/CharacterMovementReplication.h")
@:uextern @:ustruct extern class FCharacterNetworkSerializationPackedBits {
  
}
