/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Contains the TFunction that determines if a scene view extension should be valid in the given context given for the current frame.
  It also contains Guid to help identify it, given that we can't directly compare TFunctions.
**/
@:glueCppIncludes("Public/SceneViewExtensionContext.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FSceneViewExtensionIsActiveFunctor {
  
}
