/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Settings applied when building a mesh.
**/
@:glueCppIncludes("Classes/Engine/EngineTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FSkeletalMeshBuildSettings {
  
  /**
    Threshold to compare vertex position equality when computing morph target deltas.
  **/
  @:uproperty public var MorphThresholdPosition : unreal.Float32;
  
  /**
    Threshold use to decide if two UVs are equal.
  **/
  @:uproperty public var ThresholdUV : unreal.Float32;
  
  /**
    Threshold use to decide if two normal, tangents or bi-normals are equal.
  **/
  @:uproperty public var ThresholdTangentNormal : unreal.Float32;
  
  /**
    Threshold use to decide if two vertex position are equal.
  **/
  @:uproperty public var ThresholdPosition : unreal.Float32;
  
  /**
    Required for PNT tessellation but can be slow. Recommend disabling for larger meshes.
  **/
  @:uproperty public var bBuildAdjacencyBuffer : Bool;
  
  /**
    If true, UVs will be stored at full floating point precision.
  **/
  @:uproperty public var bUseFullPrecisionUVs : Bool;
  
  /**
    If true, Tangents will be stored at 16 bit vs 8 bit precision.
  **/
  @:uproperty public var bUseHighPrecisionTangentBasis : Bool;
  
  /**
    If true, degenerate triangles will be removed.
  **/
  @:uproperty public var bRemoveDegenerates : Bool;
  
  /**
    If true, we will use the surface area and the corner angle of the triangle as a ratio when computing the normals.
  **/
  @:uproperty public var bComputeWeightedNormals : Bool;
  
  /**
    If true, degenerate triangles will be removed.
  **/
  @:uproperty public var bUseMikkTSpace : Bool;
  
  /**
    If true, tangents in the raw mesh are ignored and recomputed.
  **/
  @:uproperty public var bRecomputeTangents : Bool;
  
  /**
    If true, normals in the raw mesh are ignored and recomputed.
  **/
  @:uproperty public var bRecomputeNormals : Bool;
  
}
