/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Class used to send audio to submixes from USoundBase
**/
@:glueCppIncludes("Classes/Sound/SoundSubmixSend.h")
@:uextern @:ustruct extern class FSoundSubmixSendInfo {
  
  /**
    The custom reverb send curve to use for distance-based send level.
  **/
  @:uproperty public var CustomSendLevelCurve : unreal.FRuntimeFloatCurve;
  
  /**
    The max distance to send to the master
  **/
  @:uproperty public var MaxSendDistance : unreal.Float32;
  
  /**
    The min distance to send to the master
  **/
  @:uproperty public var MinSendDistance : unreal.Float32;
  
  /**
    The amount to send to master when sound is located at a distance equal to value specified in the max send distance.
  **/
  @:uproperty public var MaxSendLevel : unreal.Float32;
  
  /**
    The amount to send to master when sound is located at a distance equal to value specified in the min send distance.
  **/
  @:uproperty public var MinSendLevel : unreal.Float32;
  
  /**
    The amount of audio to send
  **/
  @:uproperty public var SendLevel : unreal.Float32;
  
  /**
    The submix to send the audio to
  **/
  @:uproperty public var SoundSubmix : unreal.USoundSubmixBase;
  
  /**
    Defines at what mix stage the send should happen.
  **/
  @:uproperty public var SendStage : unreal.ESubmixSendStage;
  
  /**
    Manual: Use Send Level only
    Linear: Interpolate between Min and Max Send Levels based on listener distance (between Distance Min and Distance Max)
    Custom Curve: Use the float curve to map Send Level to distance (0.0-1.0 on curve maps to Distance Min - Distance Max)
  **/
  @:uproperty public var SendLevelControlMethod : unreal.ESendLevelControlMethod;
  
}
