/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Default parameter destination settings for source audio object.
**/
@:glueCppIncludes("Classes/Sound/SoundModulationDestination.h")
@:uextern @:ustruct extern class FSoundModulationDefaultRoutingSettings extends unreal.FSoundModulationDefaultSettings {
  
  /**
    What low-pass modulation settings to use
  **/
  @:uproperty public var LowpassRouting : unreal.EModulationRouting;
  
  /**
    What high-pass modulation settings to use
  **/
  @:uproperty public var HighpassRouting : unreal.EModulationRouting;
  
  /**
    What pitch modulation settings to use
  **/
  @:uproperty public var PitchRouting : unreal.EModulationRouting;
  
  /**
    What volume modulation settings to use
  **/
  @:uproperty public var VolumeRouting : unreal.EModulationRouting;
  
}
