/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  * Base class for all bone compression codecs.
**/
@:glueCppIncludes("Animation/AnimBoneCompressionCodec.h")
@:uextern @:uclass extern class UAnimBoneCompressionCodec extends unreal.UObject {
  
  /**
    Description for this codec.
  **/
  @:uproperty public var Description : unreal.FString;
  
}
