/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Engine/BlueprintGeneratedClass.h")
@:uextern @:uclass extern class UBlueprintGeneratedClass extends unreal.UClass {
  
  /**
    Mapping of changed properties & data to apply when instancing components in a cooked build (one entry per named AddComponent node template for fast lookup at runtime).
    Note: This is not currently utilized by the editor; it is a runtime optimization for cooked builds only. It assumes that the component class structure does not change.
  **/
  @:uproperty public var CookedComponentInstancingData : unreal.TMap<unreal.FName, unreal.FBlueprintCookedComponentInstancingData>;
  #if WITH_EDITORONLY_DATA
  @:uproperty public var CalledFunctions : unreal.TArray<unreal.UFunction>;
  
  /**
    Property guid map
  **/
  @:uproperty public var PropertyGuids : unreal.TMap<unreal.FName, unreal.FGuid>;
  @:uproperty public var OverridenArchetypeForCDO : unreal.UObject;
  
  /**
    This is a list of event graph call function nodes that are simple (no argument) thunks into the event graph (typically used for animation delegates, etc...)
    It is a deprecated list only used for backwards compatibility prior to VER_UE4_SERIALIZE_BLUEPRINT_EVENTGRAPH_FASTCALLS_IN_UFUNCTION.
  **/
  @:deprecated @:uproperty public var FastCallPairs_DEPRECATED : unreal.TArray<unreal.FEventGraphFastCallPair>;
  #end // WITH_EDITORONLY_DATA
  @:uproperty public var UberGraphFunction : unreal.UFunction;
  @:deprecated @:uproperty public var UberGraphFramePointerProperty_DEPRECATED : unreal.UStructProperty;
  
  /**
    Stores data to override (in children classes) components (created by SCS) from parent classes
  **/
  @:uproperty public var InheritableComponentHandler : unreal.UInheritableComponentHandler;
  
  /**
    'Simple' construction script - graph of components to instance
  **/
  @:uproperty public var SimpleConstructionScript : unreal.USimpleConstructionScript;
  
  /**
    Array of blueprint overrides of component classes in parent classes
  **/
  @:uproperty public var ComponentClassOverrides : unreal.TArray<unreal.FBPComponentClassOverride>;
  
  /**
    Array of templates for timelines that should be created
  **/
  @:uproperty public var Timelines : unreal.TArray<unreal.UTimelineTemplate>;
  
  /**
    Array of component template objects, used by AddComponent function
  **/
  @:uproperty public var ComponentTemplates : unreal.TArray<unreal.UActorComponent>;
  
  /**
    Array of objects containing information for dynamically binding delegates to functions in this blueprint
  **/
  @:uproperty public var DynamicBindingObjects : unreal.TArray<unreal.UDynamicBlueprintBinding>;
  #if WITH_EDITORONLY_DATA
  
  /**
    Used to check if this class has sparse data that can be serialized. This will be false when loading the data if it hasn't already been saved out.
  **/
  @:uproperty public var bIsSparseClassDataSerializable : Bool;
  #end // WITH_EDITORONLY_DATA
  
  /**
    Flag used to indicate if this class has data to support the component instancing fast path.
  **/
  @:uproperty public var bHasCookedComponentInstancingData : Bool;
  
  /**
    Flag used to indicate if this class has a nativized parent in a cooked build.
  **/
  @:uproperty public var bHasNativizedParent : Bool;
  @:uproperty public var NumReplicatedProperties : unreal.Int32;
  
}
