/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Materials/MaterialExpressionNamedReroute.h")
@:uextern @:uclass extern class UMaterialExpressionNamedRerouteDeclaration extends unreal.UMaterialExpressionNamedRerouteBase {
  
  /**
    The variable GUID, to support copy across graphs
  **/
  @:uproperty public var VariableGuid : unreal.FGuid;
  #if WITH_EDITORONLY_DATA
  
  /**
    The color of the graph node. The same color will apply to all linked usages of this Declaration node
  **/
  @:uproperty public var NodeColor : unreal.FLinearColor;
  #end // WITH_EDITORONLY_DATA
  @:uproperty public var Name : unreal.FName;
  
  /**
    The input pin
  **/
  @:uproperty public var Input : unreal.FExpressionInput;
  
}
