/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Physical material masks are used to map multiple physical materials to a single rendering material
**/
@:glueCppIncludes("PhysicalMaterials/PhysicalMaterialMask.h")
@:uextern @:uclass extern class UPhysicalMaterialMask extends unreal.UObject {
  
  /**
    The addressing mode to use for the Y axis.
  **/
  @:uproperty public var AddressY : unreal.TextureAddress;
  
  /**
    The addressing mode to use for the X axis.
  **/
  @:uproperty public var AddressX : unreal.TextureAddress;
  
  /**
    StaticMesh UV channel index to use when performing lookups with this mask.
  **/
  @:uproperty public var UVChannelIndex : unreal.Int32;
  #if WITH_EDITORONLY_DATA
  
  /**
    Mask input texture, square aspect ratio recommended. Recognized mask colors include: white, black, red, green, yellow, cyan, turquoise, and magenta.
  **/
  @:uproperty public var MaskTexture : unreal.UTexture;
  @:uproperty public var AssetImportData : unreal.UAssetImportData;
  #end // WITH_EDITORONLY_DATA
  
}
