/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  
**/
@:glueCppIncludes("Engine/SkeletalMeshLODSettings.h")
@:uextern @:uclass extern class USkeletalMeshLODSettings extends unreal.UDataAsset {
  @:uproperty private var LODGroups : unreal.TArray<unreal.FSkeletalMeshLODGroupSettings>;
  
  /**
    Default maximum number of optional LODs for meshes in this group (currently, need to be either 0 or > num of LODs below MinLod)
  **/
  @:uproperty private var MaxNumOptionalLODs : unreal.FPerPlatformInt;
  
  /**
    Default maximum number of streamed LODs for meshes in this group
  **/
  @:uproperty private var MaxNumStreamedLODs : unreal.FPerPlatformInt;
  
  /**
    Whether meshes in this group stream LODs by default
  **/
  @:uproperty private var bSupportLODStreaming : unreal.FPerPlatformBool;
  
  /**
    When true LODs below MinLod will not be stripped during cook.
  **/
  @:uproperty private var DisableBelowMinLodStripping : unreal.FPerPlatformBool;
  
  /**
    Minimum LOD to render. Can be overridden per component as well as set here for all mesh instances here
  **/
  @:uproperty private var MinLod : unreal.FPerPlatformInt;
  
}
