/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.contentbrowserdata;

/**
  Representation of a Content Browser item.
  
  FContentBrowserItem is potentially a composite of multiple internal items (eg, combining equivalent folder items from different data sources),
  and defers back to these internal items to provide its functionality (via the data source that owns each internal item).
**/
@:umodule("ContentBrowserData")
@:glueCppIncludes("Public/ContentBrowserItem.h")
@:uextern @:ustruct extern class FContentBrowserItem {
  
}
