/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.curveeditor;

/**
  An abstract base class for Curve Editor Filtering. If you inherit from this class your class will automatically
  show up in the Curve Editor's Filter dropdown. This allows projects to easily create custom filters to edit curve
  data as they only have to implement this class. Any UPROPERTY(EditAnywhere) properties exposed on the class will
  show up in the Curve Editor Filter panel which allows you to easily create customizable properties or advanced filters
  that rely on user supplied settings.
  
  The CDO is directly edited in the Curve Editor Filter panel so if you wish to save user settings between runs you can
  add the "config" property to your UPROPERTY() and it will automatically get saved.
**/
@:umodule("CurveEditor")
@:glueCppIncludes("Filters/CurveEditorFilterBase.h")
@:uextern @:uclass extern class UCurveEditorFilterBase extends unreal.UObject {
  
}
