/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

@:umodule("UnrealEd")
@:glueCppIncludes("Classes/Settings/LevelEditorPlayNetworkEmulationSettings.h")
@:uname("NetworkEmulationTarget")
@:class @:uextern @:uenum extern enum NetworkEmulationTarget {
  
  /**
    Server Only
  **/
  @DisplayName("Server Only")
  Server;
  
  /**
    Clients Only
  **/
  @DisplayName("Clients Only")
  Client;
  
  /**
    Everyone
  **/
  @DisplayName("Everyone")
  Any;
  
}
