/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

@:umodule("UnrealEd")
@:glueCppIncludes("Settings/EditorSettings.h")
@:uextern @:uclass extern class UEditorSettings extends unreal.UObject {
  @:uproperty public var AutoScalabilityWorkScaleAmount : unreal.Float32;
  
  /**
    The id's of the surveys currently in-progress
  **/
  @:uproperty public var InProgressSurveys : unreal.TArray<unreal.FGuid>;
  
  /**
    The id's of the surveys completed
  **/
  @:uproperty public var CompletedSurveys : unreal.TArray<unreal.FGuid>;
  @:uproperty public var bCopyStarterContentPreference : Bool;
  
  /**
    The paths of projects created with the new project wizard. This is used to populate the "Path" field of the new project dialog.
  **/
  @:uproperty public var CreatedProjectPaths : unreal.TArray<unreal.FString>;
  
  /**
    Game project files that were recently opened in the editor
  **/
  @:uproperty public var RecentlyOpenedProjectFiles : unreal.TArray<unreal.FString>;
  
  /**
    Can the editor report usage analytics (types of assets being spawned, etc...) back to Epic in order for us to improve the editor user experience?  Note: The editor must be restarted for changes to take effect.
  **/
  @:deprecated @:uproperty public var bEditorAnalyticsEnabled_DEPRECATED : Bool;
  
  /**
    When checked, the most recently loaded project will be auto-loaded at editor startup if no other project was specified on the command line
  **/
  @:uproperty public var bLoadTheMostRecentlyLoadedProjectAtStartup : Bool;
  
  /**
    Adjusts the local global DDC caching location for AWS/S3 downloaded package bundles.
    This affects every project on your computer that uses the UE-S3DataCachePath environment variable override.
  **/
  @:uproperty public var GlobalS3DDCPath : unreal.FDirectoryPath;
  
  /**
    Whether to enable the S3 derived data cache backend
  **/
  @:uproperty public var bEnableS3DDC : Bool;
  
  /**
    Path to a network share that can be used for sharing derived data (native textures, compiled shaders, etc...) with a team. Will not disabled if this directory
    cannot be accessed. The editor must be restarted for changes to take effect, this will override the 'Global Network DDC Path'
  **/
  @:uproperty public var SharedDerivedDataCache : unreal.FDirectoryPath;
  
  /**
    Directory to be used for caching derived data locally (native textures, compiled shaders, etc...). The editor must be restarted for changes to take effect.
    This will override the 'Global Local DDC Path'.
  **/
  @:uproperty public var LocalDerivedDataCache : unreal.FDirectoryPath;
  
  /**
    Adjusts the network or shared global DDC caching location.  This is one of the areas queried after Local fails.
    This affects every project on your computer that uses the UE-SharedDataCachePath environment variable override.
  **/
  @:uproperty public var GlobalSharedDDCPath : unreal.FDirectoryPath;
  
  /**
    Adjusts the local global DDC caching location.  This affects every project on your computer that uses the
    UE-LocalDataCachePath environment variable to determine if we're overriding the Local DDC Path, this
    is the first location ANY project that doesn't override the DDC path will look for a cache texture, shader...etc.
  **/
  @:uproperty public var GlobalLocalDDCPath : unreal.FDirectoryPath;
  
}
