/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

/**
  WARNING: This type was not defined as DLL export on its declaration. Because of that, some of its methods are inaccessible
  
  * Commandlet used to validate the package saving mechanism.
  * It can currently compare the saving of a package (or folder of packages) between UPackage::Save and UPackage::Save2
**/
@:umodule("UnrealEd")
@:glueCppIncludes("Commandlets/SavePackageUtilitiesCommandlet.h")
@:noClass @:uextern @:uclass extern class USavePackageUtilitiesCommandlet extends unreal.UCommandlet {
  
}
