/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  AGizmoActor is a base class for Actors that would be created to represent Gizmos in the scene.
  Currently this does not involve any special functionality, but a set of static functions
  are provided to create default Components commonly used in Gizmos.
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("BaseGizmos/GizmoActor.h")
@:uextern @:uclass extern class AGizmoActor extends unreal.interactivetoolsframework.AInternalToolFrameworkActor {
  
}
