/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("BaseGizmos/GizmoInterfaces.h")
@:uextern @:uclass extern interface IGizmoAxisSource {
  
  /**
    @return Origin Point of axis
  **/
  @:ufunction @:thisConst public function GetOrigin() : unreal.FVector;
  
  /**
    @return Direction Vector of axis
  **/
  @:ufunction @:thisConst public function GetDirection() : unreal.FVector;
  
  /**
    @return true if this AxisSource has tangent vectors orthogonal to the Direction vector
  **/
  @:ufunction @:thisConst public function HasTangentVectors() : Bool;
  
  /**
    Get the two tangent vectors that are orthogonal to the Direction vector.
    @warning Only valid if HasTangentVectors() returns true
  **/
  @:ufunction @:thisConst public function GetTangentVectors(TangentXOut : unreal.PRef<unreal.FVector>, TangentYOut : unreal.PRef<unreal.FVector>) : Void;
  
}
