/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  UGizmoLocalFloatParameterSource is an implementation of IGizmoFloatParameterSource
  (by way of UGizmoBaseFloatParameterSource) which locally stores the relevant Parameter
  and emits update events via the OnParameterChanged delegate.
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("BaseGizmos/ParameterSourcesFloat.h")
@:uextern @:uclass extern class UGizmoLocalFloatParameterSource extends unreal.interactivetoolsframework.UGizmoBaseFloatParameterSource {
  @:uproperty public var LastChange : unreal.interactivetoolsframework.FGizmoFloatParameterChange;
  @:uproperty public var Value : unreal.Float32;
  
}
