/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Flags that camera shakes can return to change base-class behaviour.
**/
@:glueCppIncludes("Classes/Camera/CameraShakeBase.h")
@:uname("ECameraShakeUpdateResultFlags")
@:class @:uextern @:uenum extern enum ECameraShakeUpdateResultFlags {
  
  /**
    Apply the result location, rotation, and field of view as absolute values, instead of additive values.
  **/
  ApplyAsAbsolute;
  
  /**
    Do not apply scaling (dynamic scale, blending weight, shake scale), meaning that this will be done in the sub-class. Implied when ApplyAsAbsolute is set.
  **/
  SkipAutoScale;
  
  /**
    Do not re-orient the result based on the play-space. Implied when ApplyAsAbsolute is set.
  **/
  SkipAutoPlaySpace;
  
  /**
    Default flags: the sub-class is returning local, additive offsets, and lets the base class take care of the rest.
  **/
  Default;
  
}
