/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Public/Animation/AnimTypes.h")
@:uname("ECurveBlendOption.Type")
@:uextern @:uenum extern enum ECurveBlendOption {
  
  /**
    Last pose that contains valid curve value override it.
  **/
  Override;
  
  /**
    Only set the value if the previous pose doesn't have the curve value.
  **/
  DoNotOverride;
  
  /**
    Normalize By Sum of Weight and use it to blend.
  **/
  NormalizeByWeight;
  
  /**
    Blend By Weight without normalizing
  **/
  BlendByWeight;
  
  /**
    Use Base Pose for all curve values. Do not blend
  **/
  UseBasePose;
  
  /**
    Find the highest curve value from multiple poses and use that.
  **/
  UseMaxValue;
  
  /**
    Find the lowest curve value from multiple poses and use that.
  **/
  UseMinValue;
  
}
