/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Method used when retrieving a Custom Attribute value
**/
@:glueCppIncludes("Classes/Components/SkeletalMeshComponent.h")
@:uname("ECustomBoneAttributeLookup")
@:class @:uextern @:uenum extern enum ECustomBoneAttributeLookup {
  
  /**
    Only look for the attribute using the provided bone (name)
  **/
  BoneOnly;
  
  /**
    Look for the attribute using the provided bone (name) and its direct parent bone
  **/
  ImmediateParent;
  
  /**
    Look for the attribute using the provided bone (name) and its direct bone parent hierarchy up and until the root bone
  **/
  ParentHierarchy;
  
}
