/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Inertialization: High-Performance Animation Transitions in 'Gears of War'
  David Bollo
  Game Developer Conference 2018
  
  https:www.gdcvault.com/play/1025165/Inertialization
  https:www.gdcvault.com/play/1025331/Inertialization
**/
@:glueCppIncludes("Classes/Animation/AnimNode_Inertialization.h")
@:uname("EInertializationState")
@:class @:uextern @:uenum extern enum EInertializationState {
  Inactive;
  
  /**
    Inertialization inactive
  **/
  Pending;
  
  /**
    Inertialization request pending... prepare to capture the pose difference and then switch to active
  **/
  Active;
  
}
