/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Engine/EngineTypes.h")
@:uname("EMaterialShadingRate")
@:uextern @:uenum extern enum EMaterialShadingRate {
  
  /**
    1x1
  **/
  @DisplayName("1x1")
  MSR_1x1;
  
  /**
    2x1
  **/
  @DisplayName("2x1")
  MSR_2x1;
  
  /**
    1x2
  **/
  @DisplayName("1x2")
  MSR_1x2;
  
  /**
    2x2
  **/
  @DisplayName("2x2")
  MSR_2x2;
  
  /**
    4x2
  **/
  @DisplayName("4x2")
  MSR_4x2;
  
  /**
    2x4
  **/
  @DisplayName("2x4")
  MSR_2x4;
  
  /**
    4x4
  **/
  @DisplayName("4x4")
  MSR_4x4;
  MSR_Count;
  
}
