/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Engine/EngineTypes.h")
@:uname("EMaterialStencilCompare")
@:uextern @:uenum extern enum EMaterialStencilCompare {
  
  /**
    Less Than
  **/
  @DisplayName("Less Than")
  MSC_Less;
  
  /**
    Less Than or Equal
  **/
  @DisplayName("Less Than or Equal")
  MSC_LessEqual;
  
  /**
    Greater Than
  **/
  @DisplayName("Greater Than")
  MSC_Greater;
  
  /**
    Greater Than or Equal
  **/
  @DisplayName("Greater Than or Equal")
  MSC_GreaterEqual;
  
  /**
    Equal
  **/
  @DisplayName("Equal")
  MSC_Equal;
  
  /**
    Not Equal
  **/
  @DisplayName("Not Equal")
  MSC_NotEqual;
  
  /**
    Never
  **/
  @DisplayName("Never")
  MSC_Never;
  
  /**
    Always
  **/
  @DisplayName("Always")
  MSC_Always;
  MSC_Count;
  
}
