/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Components/LODSyncComponent.h")
@:uname("ESyncOption")
@:class @:uextern @:uenum extern enum ESyncOption {
  
  /**
    Drive LOD from this component. It will contribute to the change of LOD
  **/
  Drive;
  
  /**
    It follows what's currently driven by other components. It doesn't contribute to the change of LOD
  **/
  Passive;
  
  /**
    It is disabled, it doesn't do anything
  **/
  Disabled;
  
}
