/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Animation/AnimNode_LinkedAnimGraph.h")
@:uextern @:ustruct extern class FAnimNode_LinkedAnimGraph extends unreal.FAnimNode_CustomProperty {
  
  /**
    Whether named notifies will be propagated from this linked instance to other instances (outer or other linked instances)
  **/
  @:uproperty public var bPropagateNotifiesToLinkedInstances : Bool;
  
  /**
    Whether named notifies will be received by this linked instance from other instances (outer or other linked instances)
  **/
  @:uproperty public var bReceiveNotifiesFromLinkedInstances : Bool;
  
  /**
    Optional tag used to identify this linked instance
  **/
  @:uproperty public var Tag : unreal.FName;
  
  /**
    The class spawned for this linked instance
  **/
  @:uproperty public var InstanceClass : unreal.TSubclassOf<unreal.UAnimInstance>;
  
  /**
    List of input pose names, 1-1 with pose links about, built by the compiler
  **/
  @:uproperty public var InputPoseNames : unreal.TArray<unreal.FName>;
  
  /**
    Input poses for the node, intentionally not accessible because if there's no input
    nodes in the target class we don't want to show these as pins
  **/
  @:uproperty public var InputPoses : unreal.TArray<unreal.FPoseLink>;
  
}
