/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  (Baked) int32 custom attribute, uses FIntegralCurve for evaluation instead of FVariant array
**/
@:glueCppIncludes("Classes/Animation/CustomAttributes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FBakedIntegerCustomAttribute {
  @:uproperty public var IntCurve : unreal.FIntegralCurve;
  @:uproperty public var AttributeName : unreal.FName;
  
}
