/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Utility struct to store class overrides for components.
**/
@:glueCppIncludes("Classes/Engine/BlueprintGeneratedClass.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FBPComponentClassOverride {
  
  /**
    The class to use when constructing the component.
  **/
  @:uproperty public var ComponentClass : unreal.UClass;
  
  /**
    The component name an override is being specified for.
  **/
  @:uproperty public var ComponentName : unreal.FName;
  
}
