/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Describe a LODActor ISM component
**/
@:glueCppIncludes("Public/HLOD/HLODProxyDesc.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FHLODISMComponentDesc {
  @:uproperty public var Instances : unreal.TArray<unreal.FTransform>;
  @:uproperty public var Material : unreal.UMaterialInterface;
  @:uproperty public var StaticMesh : unreal.UStaticMesh;
  
}
