/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

/**
  Movie scene sequence transform class that transforms from one time-space to another.
  
  @note The transform can be thought of as the top row of a 2x2 matrix, where the bottom row is the identity:
                      | TimeScale     Offset  |
                      | 0                     1               |
  
  As such, traditional matrix mathematics can be applied to transform between different sequence's time-spaces.
  
  Transforms apply time scale first, and then offset.
**/
@:umodule("MovieScene")
@:glueCppIncludes("Public/Evaluation/MovieSceneTimeTransform.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMovieSceneTimeTransform {
  
  /**
    Scalar frame offset applied after the scale
  **/
  @:uproperty public var Offset : unreal.FFrameTime;
  
  /**
    The sequence's time scale (or play rate)
  **/
  @:uproperty public var TimeScale : unreal.Float32;
  
}
