/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.livelink;

/**
  WARNING: This type was not defined as DLL export on its declaration. Because of that, some of its methods are inaccessible
  
  VirtualSubjectSource Settings to be able to differentiate from live sources and keep a name associated to the source
**/
@:umodule("LiveLink")
@:glueCppIncludes("Private/LiveLinkVirtualSource.h")
@:noClass @:uextern @:uclass extern class ULiveLinkVirtualSubjectSourceSettings extends unreal.livelinkinterface.ULiveLinkSourceSettings {
  @:uproperty public var SourceName : unreal.FName;
  
}
