/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.fieldsystemengine;

/**
  Set a uniform integer value independently of the sample position. The output is equal to magnitude
**/
@:umodule("FieldSystemEngine")
@:glueCppIncludes("Field/FieldSystemObjects.h")
@:uextern @:uclass extern class UUniformInteger extends unreal.fieldsystemengine.UFieldNodeInt {
  
  /**
    The field output will be equal the magnitude
  **/
  @:uproperty public var Magnitude : unreal.Int32;
  
  /**
    Set a uniform integer value independently of the sample position. The output is equal to magnitude
    @param    Magnitude The field output will be equal the magnitude
  **/
  @:ufunction(BlueprintCallable) @:final public function SetUniformInteger(@:bpopt("0") Magnitude : unreal.Int32) : unreal.fieldsystemengine.UUniformInteger;
  
}
