/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.livelinkeditor;

@:umodule("LiveLinkEditor")
@:glueCppIncludes("Private/LiveLinkTest.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FLiveLinkInnerTestInternal {
  @:uproperty public var InnerIntArray : unreal.TArray<unreal.Int32>;
  @:uproperty public var InnerSingleInt : unreal.Int32;
  @:uproperty public var InnerSingleFloat : unreal.Float32;
  
}
