/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

/**
  Helper struct for setting string console ini values.
**/
@:umodule("UnrealEd")
@:glueCppIncludes("Classes/Editor/AssetGuideline.h")
@:uextern @:ustruct extern class FIniStringValue {
  
  /**
    From .ini, relative to {PROJECT}. Ex: /Config/DefaultEngine.ini
  **/
  @:uproperty public var Filename : unreal.FString;
  
  /**
    From .ini. Ex: True
  **/
  @:uproperty public var Value : unreal.FString;
  
  /**
    From .ini. Ex: r.GPUSkin.Support16BitBoneIndex
  **/
  @:uproperty public var Key : unreal.FString;
  
  /**
    From .ini. Ex: /Script/Engine.RendererSettings
  **/
  @:uproperty public var Section : unreal.FString;
  
}
