/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

/**
  Implements Editor settings for experimental features.
**/
@:umodule("UnrealEd")
@:glueCppIncludes("Settings/EditorExperimentalSettings.h")
@:uextern @:uclass extern class UEditorExperimentalSettings extends unreal.UObject {
  
  /**
    Allows creation of assets with paths longer than 260 characters. Note that this also requires the Windows 10 Anniversary Update (1607), and support for long paths to be enabled through the group policy editor.
  **/
  @:uproperty public var bEnableLongPathsSupport : Bool;
  
  /**
    When creating new Material Layers and Material Layer Blends, set up example graphs.
  **/
  @:uproperty public var bExampleLayersAndBlends : Bool;
  
  /**
    Enables in-editor support for text asset formats
  **/
  @:uproperty public var bTextAssetFormatSupport : Bool;
  
  /**
    Enable experimental PIE preview device launch
  **/
  @:uproperty public var bMobilePIEPreviewDeviceLaunch : Bool;
  
  /**
    Enable experimental bulk facial animation importer (found in Developer Tools menu, requires editor restart)
  **/
  @:uproperty public var bFacialAnimationImporter : Bool;
  
  /**
    Allows editing of potentially unsafe properties during PIE. Advanced use only - use with caution.
  **/
  @:uproperty public var bAllowPotentiallyUnsafePropertyEditing : Bool;
  
  /**
    Whether to use OpenCL to accelerate convex hull decomposition (uses GPU to decrease time taken to decompose meshes, currently only available on Mac OS X)
  **/
  @:uproperty public var bUseOpenCLForConvexHullDecomp : Bool;
  
  /**
    Enable multithreaded shadow map encoding (decreases time taken to encode shadow maps)
  **/
  @:uproperty public var bEnableMultithreadedShadowmapEncoding : Bool;
  
  /**
    Enable multithreaded lightmap encoding (decreases time taken to encode lightmaps)
  **/
  @:uproperty public var bEnableMultithreadedLightmapEncoding : Bool;
  
  /**
    Allow Vulkan Preview
  **/
  @:uproperty public var bAllowVulkanPreview : Bool;
  
  /**
    Enable late joining in PIE
  **/
  @:uproperty public var bAllowLateJoinInPIE : Bool;
  @:uproperty public var MultiProcessCooking : unreal.Int32;
  @:uproperty public var bSharedCookedBuilds : Bool;
  
  /**
    Disable cook in the editor
  **/
  @:uproperty public var bDisableCookInEditor : Bool;
  
  /**
    Allows ChunkIDs to be assigned to assets to via the content browser context menu.
  **/
  @:uproperty public var bContextMenuChunkAssignments : Bool;
  
  /**
    , Category=Blueprints, meta=(DisplayName="Draw midpoint arrows in Blueprints")
  **/
  @:uproperty public var bDrawMidpointArrowsInBlueprints : Bool;
  @:uproperty private var ResolvedBaseClassesToAllowRecompilingDuringPlayInEditor : unreal.TArray<unreal.UClass>;
  
  /**
    Allows the One File Per Actor option for worlds
  **/
  @:uproperty public var bEnableOneFilePerActorSupport : Bool;
  
  /**
    Break on Exceptions allows you to trap Access Nones and other exceptional events in Blueprints.
  **/
  @:uproperty public var bBreakOnExceptions : Bool;
  
  /**
    Allows for customization of toolbars and menus throughout the editor
  **/
  @:uproperty public var bToolbarCustomization : Bool;
  
  /**
    Specify which console-specific nomenclature to use for gamepad label text
  **/
  @:uproperty public var ConsoleForGamepadLabels : unreal.inputcore.EConsoleForGamepadLabels;
  
  /**
    When enabled, all details panels will be able to have properties marked as favorite that show in a top most category.
    NOTE: Some customizations are not supported yet
  **/
  @:uproperty public var bEnableFavoriteSystem : Bool;
  
  /**
    Allows usage of the Translation Picker
  **/
  @:uproperty public var bEnableTranslationPicker : Bool;
  
  /**
    Allows usage of the Localization Dashboard
  **/
  @:uproperty public var bEnableLocalizationDashboard : Bool;
  
  /**
    Allows usage of the procedural foliage system
  **/
  @:uproperty public var bProceduralFoliage : Bool;
  
  /**
    The brightness of the slate UI on HDR monitors
  **/
  @:uproperty public var HDREditorNITLevel : unreal.Float32;
  
  /**
    Allows the editor to run on HDR monitors on Windows 10
  **/
  @:uproperty public var bHDREditor : Bool;
  
}
