/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  FInputCaptureUpdate uses this type to indicate what state the capturing Behavior
  would like to transition to, based on the input event
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("Public/InputBehavior.h")
@:uname("EInputCaptureState")
@:class @:uextern @:uenum extern enum EInputCaptureState {
  Begin;
  
  /**
    start capturing (which should always be the case if BeginCapture is called)
  **/
  Continue;
  
  /**
    Behavior wants to continue capturing
  **/
  End;
  
  /**
    Behavior wants to end capturing
  **/
  Ignore;
  
}
