/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  FGizmoVec2ParameterChange represents a change in the value of an IGizmoFloatParameterSource.
  IGizmoFloatParameterSource implementations use this to track changes and emit delta information.
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("Public/BaseGizmos/ParameterSourcesFloat.h")
@:uextern @:ustruct extern class FGizmoFloatParameterChange {
  @:uproperty public var CurrentValue : unreal.Float32;
  @:uproperty public var InitialValue : unreal.Float32;
  
}
