/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  Standard properties for a Brush-type Tool
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("BaseTools/BaseBrushTool.h")
@:uextern @:uclass extern class UBrushBaseProperties extends unreal.interactivetoolsframework.UInteractiveToolPropertySet {
  
  /**
    If false, then BrushFalloffAmount will not be shown in DetailsView panels (otherwise no effect)
  **/
  @:uproperty public var bShowFalloff : Bool;
  
  /**
    If false, then BrushStrength will not be shown in DetailsView panels (otherwise no effect)
  **/
  @:uproperty public var bShowStrength : Bool;
  
  /**
    Amount of falloff to apply (0.0 - 1.0)
  **/
  @:uproperty public var BrushFalloffAmount : unreal.Float32;
  
  /**
    Strength of the brush (0.0 - 1.0)
  **/
  @:uproperty public var BrushStrength : unreal.Float32;
  
  /**
    Radius of brush
  **/
  @:uproperty public var BrushRadius : unreal.Float32;
  
  /**
    If true, ignore relative Brush Size and use explicit world Radius
  **/
  @:uproperty public var bSpecifyRadius : Bool;
  
  /**
    Relative size of brush
  **/
  @:uproperty public var BrushSize : unreal.Float32;
  
}
