/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  UGizmoBaseVec2ParameterSource is an implementation of IGizmoVec2ParameterSource
  (by way of UGizmoBaseVec2ParameterSource) which locally stores the relevant Parameter
  and emits update events via the OnParameterChanged delegate.
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("BaseGizmos/ParameterSourcesVec2.h")
@:uextern @:uclass extern class UGizmoLocalVec2ParameterSource extends unreal.interactivetoolsframework.UGizmoBaseVec2ParameterSource {
  @:uproperty public var LastChange : unreal.interactivetoolsframework.FGizmoVec2ParameterChange;
  @:uproperty public var Value : unreal.FVector2D;
  
}
