/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  Simple Component intended to be used as part of 3D Gizmos.
  Draws outline of 3D rectangle based on parameters.
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("BaseGizmos/GizmoRectangleComponent.h")
@:uextern @:uclass extern class UGizmoRectangleComponent extends unreal.interactivetoolsframework.UGizmoBaseComponent {
  @:uproperty public var SegmentFlags : unreal.UInt8;
  @:uproperty public var Thickness : unreal.Float32;
  @:uproperty public var LengthY : unreal.Float32;
  @:uproperty public var LengthX : unreal.Float32;
  @:uproperty public var OffsetY : unreal.Float32;
  @:uproperty public var OffsetX : unreal.Float32;
  @:uproperty public var DirectionY : unreal.FVector;
  @:uproperty public var DirectionX : unreal.FVector;
  
}
