/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.interactivetoolsframework;

/**
  UInputBehaviorSet manages a set of UInputBehaviors, and provides various functions
  to query and forward events to the set. Tools and Widgets provide instances of this via
  IInputBehaviorSource, and UInputRouter collects and manages them (see comments there)
  
  Behaviors in the set each have a source pointer and group tag, which allows sets of
  behaviors to be managed together. For example one UInputBehaviorSet can be merged into
  another and removed later.
**/
@:umodule("InteractiveToolsFramework")
@:glueCppIncludes("InputBehaviorSet.h")
@:uextern @:uclass extern class UInputBehaviorSet extends unreal.UObject {
  
  /**
    Current set of known Behaviors
  **/
  @:uproperty private var Behaviors : unreal.TArray<unreal.interactivetoolsframework.FBehaviorInfo>;
  
}
