/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.variantmanagercontent;

@:umodule("VariantManagerContent")
@:glueCppIncludes("Variant.h")
@:uextern @:uclass extern class UVariant extends unreal.UObject {
  @:ufunction(BlueprintCallable) @:final public function GetParent() : unreal.variantmanagercontent.UVariantSet;
  @:ufunction(BlueprintCallable) @:final public function SetDisplayText(NewDisplayText : unreal.Const<unreal.PRef<unreal.FText>>) : Void;
  @:ufunction(BlueprintCallable) @:thisConst @:final public function GetDisplayText() : unreal.FText;
  @:ufunction(BlueprintCallable) @:final public function GetNumActors() : unreal.Int32;
  @:ufunction(BlueprintCallable) @:final public function GetActor(ActorIndex : unreal.Int32) : unreal.AActor;
  @:ufunction(BlueprintCallable) @:final public function SwitchOn() : Void;
  
  /**
    Returns true if none of our properties are dirty
  **/
  @:ufunction(BlueprintCallable) @:final public function IsActive() : Bool;
  
  /**
    Sets the thumbnail to use for this variant. Can receive nullptr to clear it
  **/
  @:ufunction(BlueprintCallable) @:final public function SetThumbnailFromTexture(NewThumbnail : unreal.UTexture2D) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetThumbnailFromFile(FilePath : unreal.FString) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetThumbnailFromCamera(WorldContextObject : unreal.UObject, CameraTransform : unreal.Const<unreal.PRef<unreal.FTransform>>, FOVDegrees : unreal.Float32 = 50.000000, MinZ : unreal.Float32 = 50.000000, Gamma : unreal.Float32 = 2.200000) : Void;
  
  /**
    Sets the thumbnail from the active editor viewport. Doesn't do anything if the Editor is not available
  **/
  @:ufunction(BlueprintCallable) @:final public function SetThumbnailFromEditorViewport() : Void;
  
  /**
    Gets the thumbnail currently used for this variant
  **/
  @:ufunction(BlueprintCallable) @:final public function GetThumbnail() : unreal.UTexture2D;
  
  /**
    Returns all the variants that have this variant as a dependency
  **/
  @:ufunction(BlueprintCallable) @:final public function GetDependents(LevelVariantSets : unreal.variantmanagercontent.ULevelVariantSets, bOnlyEnabledDependencies : Bool) : unreal.TArray<unreal.variantmanagercontent.UVariant>;
  @:ufunction @:final public function AddDependency(Dependency : unreal.PRef<unreal.variantmanagercontent.FVariantDependency>) : unreal.Int32;
  
  /**
    Get the dependency at index 'Index' by value. Will crash if index is invalid
  **/
  @:ufunction(BlueprintCallable) @:final public function GetDependency(Index : unreal.Int32) : unreal.variantmanagercontent.FVariantDependency;
  @:ufunction @:final public function SetDependency(Index : unreal.Int32, Dependency : unreal.PRef<unreal.variantmanagercontent.FVariantDependency>) : Void;
  @:ufunction @:final public function DeleteDependency(Index : unreal.Int32) : Void;
  @:ufunction(BlueprintCallable) @:final public function GetNumDependencies() : unreal.Int32;
  
}
