/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.vreditor;

/**
  Creation parameters for AVREditorFloatingUI
**/
@:umodule("VREditor")
@:glueCppIncludes("UI/VREditorFloatingUI.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FVREditorFloatingUICreationContext {
  
  /**
    If bHideWindowHandles is false, this window doesn't have a close button. (
  **/
  @:uproperty public var bNoCloseButton : Bool;
  
  /**
    Turn off the widget's background to create a see-through look.
  **/
  @:uproperty public var bMaskOutWidgetBackground : Bool;
  
  /**
    Turn off handles under window? (X-To-Close, movement bar...)
  **/
  @:uproperty public var bHideWindowHandles : Bool;
  
  /**
    Optional override for "VREd.EditorUISize". Leave at 0 for default.
  **/
  @:uproperty public var EditorUISize : unreal.Float32;
  
  /**
    Optional custom mesh to use for the VR window.
  **/
  @:uproperty public var PanelMesh : unreal.UStaticMesh;
  
  /**
    Panel size. Should match the size of the UMG passed in.
  **/
  @:uproperty public var PanelSize : unreal.FVector2D;
  
  /**
    Optional offset from HMD where the window opens. Pass FTransform::Identity for default logic - window will open at controller location.
  **/
  @:uproperty public var PanelSpawnOffset : unreal.FTransform;
  @:uproperty public var ParentActor : unreal.AActor;
  
  /**
    ID that the UI system will use to identify the panel. MUST BE UNIQUE!
  **/
  @:uproperty public var PanelID : unreal.FName;
  
  /**
    Widget to open in the VR window. null to close an open window (if if matches the PanelID)
  **/
  @:uproperty public var WidgetClass : unreal.TSubclassOf<unreal.umg.UUserWidget>;
  
}
