/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.magicleapplanes;

/**
  Persistent query types.
**/
@:umodule("MagicLeapPlanes")
@:glueCppIncludes("Public/MagicLeapPlanesTypes.h")
@:uname("EMagicLeapPlaneQueryType")
@:class @:uextern @:uenum extern enum EMagicLeapPlaneQueryType {
  
  /**
    All planes will be returned every query.
  **/
  Bulk;
  
  /**
    Planes will be returned as an array of new and removed planes in relation to the previous request.
  **/
  Delta;
  
}
