/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.onlinesubsystemutils;

@:umodule("OnlineSubsystemUtils")
@:glueCppIncludes("Classes/InAppPurchaseQueryCallbackProxy2.h")
@:uname("EOnlineProxyStoreOfferDiscountType")
@:class @:uextern @:uenum extern enum EOnlineProxyStoreOfferDiscountType {
  
  /**
    Offer isn't on sale
    @DisplayName NotOnSale
  **/
  @DisplayName("NotOnSale")
  NotOnSale;
  
  /**
    Offer price should be displayed as a percentage of regular price
    @DisplayName Percentage
  **/
  @DisplayName("Percentage")
  Percentage;
  
  /**
    Offer price should be displayed as an amount off regular price
    @DisplayName DiscountAmount
  **/
  @DisplayName("DiscountAmount")
  DiscountAmount;
  
  /**
    Offer price should be displayed as a new price
    @DisplayName PayAmount
  **/
  @DisplayName("PayAmount")
  PayAmount;
  
}
