/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.onlinesubsystemutils;

/**
  Platform mapping for crossplay checks
**/
@:umodule("OnlineSubsystemUtils")
@:glueCppIncludes("Public/PartyBeaconState.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FPartyBeaconCrossplayPlatformMapping {
  
  /**
    Platform type the name is mapped to (eg PlatformName=Win, PlatformType=OTHER)
  **/
  @:uproperty public var PlatformType : unreal.FString;
  
  /**
    Platform name (eg WIN)
  **/
  @:uproperty public var PlatformName : unreal.FString;
  
}
