/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.meshpaintingtoolset;

@:umodule("MeshPaintingToolset")
@:glueCppIncludes("MeshTexturePaintingTool.h")
@:uextern @:uclass extern class UMeshTexturePaintingToolProperties extends unreal.interactivetoolsframework.UBrushBaseProperties {
  
  /**
    Whether back-facing triangles should be ignored
  **/
  @:uproperty public var bOnlyFrontFacingTriangles : Bool;
  
  /**
    Enables "Flow" painting where paint is continually applied from the brush every tick
  **/
  @:uproperty public var bEnableFlow : Bool;
  
  /**
    Texture to which Painting should be Applied
  **/
  @:uproperty public var PaintTexture : unreal.UTexture2D;
  
  /**
    Seam painting flag, True if we should enable dilation to allow the painting of texture seams
  **/
  @:uproperty public var bEnableSeamPainting : Bool;
  
  /**
    UV channel which should be used for paint textures
  **/
  @:uproperty public var UVChannel : unreal.Int32;
  
  /**
    Whether or not to apply Texture Color Painting to the Alpha Channel
  **/
  @:uproperty public var bWriteAlpha : Bool;
  
  /**
    Whether or not to apply Texture Color Painting to the Blue Channel
  **/
  @:uproperty public var bWriteBlue : Bool;
  
  /**
    Whether or not to apply Texture Color Painting to the Green Channel
  **/
  @:uproperty public var bWriteGreen : Bool;
  
  /**
    Whether or not to apply Texture Color Painting to the Red Channel
  **/
  @:uproperty public var bWriteRed : Bool;
  
  /**
    Color used for Erasing Texture Color Painting
  **/
  @:uproperty public var EraseColor : unreal.FLinearColor;
  
  /**
    Color used for Applying Texture Color Painting
  **/
  @:uproperty public var PaintColor : unreal.FLinearColor;
  
}
