/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.assettags;

@:umodule("AssetTags")
@:glueCppIncludes("Public/AssetTagsSubsystem.h")
@:uname("ECollectionScriptingShareType")
@:class @:uextern @:uenum extern enum ECollectionScriptingShareType {
  
  /**
    This collection is only visible to you and is not in source control.
  **/
  Local;
  
  /**
    This collection is only visible to you.
  **/
  Private;
  
  /**
    This collection is visible to everyone.
  **/
  Shared;
  
}
