/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.umg;

/**
  A special box panel that auto-generates its entries at both design-time and runtime.
  Useful for cases where you can have a varying number of entries, but it isn't worth the effort or conceptual overhead to set up a list/tile view.
  Note that entries here are *not* virtualized as they are in the list views, so generally this should be avoided if you intend to scroll through lots of items.
  
  No children can be manually added in the designer - all are auto-generated based on the given entry class.
**/
@:umodule("UMG")
@:glueCppIncludes("UMG.h")
@:uextern @:uclass extern class UDynamicEntryBox extends unreal.umg.UDynamicEntryBoxBase {
  #if WITH_EDITORONLY_DATA
  @:uproperty public var NumDesignerPreviewEntries : unreal.Int32;
  #end // WITH_EDITORONLY_DATA
  
  /**
    Clear out the box entries, optionally deleting the underlying Slate widgets entirely as well.
  **/
  @:ufunction(BlueprintCallable) @:final public function Reset(bDeleteWidgets : Bool = false) : Void;
  @:ufunction(BlueprintCallable) @:final public function RemoveEntry(EntryWidget : unreal.umg.UUserWidget) : Void;
  
}
