/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.toolmenus;

/**
  @param Context
  @param ReturnValue
  
**/
@:glueCppIncludes("Public/ToolMenuDelegates.h")
@:uParamName("Context")
@:uParamName("ReturnValue")
@:umodule("ToolMenus")
typedef FToolMenuDynamicCanExecuteAction = unreal.DynamicDelegate<FToolMenuDynamicCanExecuteAction, unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>->Bool>;