/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.toolmenus;

@:umodule("ToolMenus")
@:glueCppIncludes("ToolMenuEntryScript.h")
@:uextern @:uclass extern class UToolMenuEntryScript extends unreal.UObject {
  @:uproperty public var Data : unreal.toolmenus.FToolMenuEntryScriptData;
  @:ufunction(BlueprintImplementableEvent) public function Execute(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : Void;
  @:ufunction(BlueprintNativeEvent) @:thisConst public function CanExecute(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : Bool;
  @:ufunction(BlueprintNativeEvent) @:thisConst public function GetCheckState(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : unreal.slatecore.ECheckBoxState;
  @:ufunction(BlueprintNativeEvent) @:thisConst public function IsVisible(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : Bool;
  @:ufunction(BlueprintNativeEvent) @:thisConst public function GetLabel(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : unreal.FText;
  @:ufunction(BlueprintNativeEvent) @:thisConst public function GetToolTip(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : unreal.FText;
  @:ufunction(BlueprintNativeEvent) @:thisConst public function GetIcon(Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : unreal.toolmenus.FScriptSlateIcon;
  @:ufunction(BlueprintImplementableEvent) public function ConstructMenuEntry(Menu : unreal.toolmenus.UToolMenu, SectionName : unreal.Const<unreal.FName>, Context : unreal.Const<unreal.PRef<unreal.toolmenus.FToolMenuContext>>) : Void;
  @:ufunction(BlueprintCallable) @:final public function RegisterMenuEntry() : Void;
  @:ufunction(BlueprintCallable) @:final public function InitEntry(OwnerName : unreal.Const<unreal.FName>, Menu : unreal.Const<unreal.FName>, Section : unreal.Const<unreal.FName>, Name : unreal.Const<unreal.FName>, Label : unreal.Const<unreal.PRef<unreal.FText>>, ToolTip : unreal.Const<unreal.PRef<unreal.FText>>) : Void;
  
}
