/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.sequencer;

/**
  Struct type that is generated from an FMovieSceneChannel type to create a single edit interface for a key/value pair
**/
@:umodule("Sequencer")
@:glueCppIncludes("SequencerKeyStructGenerator.h")
@:uextern @:uclass extern class UMovieSceneKeyStructType extends unreal.UScriptStruct {
  
}
