/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.magicleap;

@:umodule("MagicLeap")
@:glueCppIncludes("Public/LuminApplicationLifecycleComponent.h")
@:uname("EFocusLostReason")
@:class @:uextern @:uenum extern enum EFocusLostReason {
  
  /**
    Value returned when focus is lost due to an unknown event
  **/
  EFocusLostReason_Invalid;
  
  /**
    Value returned when focus is lost due to a system dialog.
  **/
  EFocusLostReason_System;
  
}
