/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.clothingsystemruntimeinterface;

/**
  These settings are shared between all instances on a skeletal mesh
  Deprecated, use UClothConfigBase instead.
**/
@:umodule("ClothingSystemRuntimeInterface")
@:glueCppIncludes("ClothConfigBase.h")
@:uextern @:uclass extern class UDEPRECATED_ClothSharedSimConfigBase extends unreal.UObject {
  
}
