/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.magicleaparpin;

/**
  This represents a collection of filters and modifiers used by to curate the ARPins search.
**/
@:umodule("MagicLeapARPin")
@:glueCppIncludes("Public/MagicLeapARPinTypes.h")
@:uextern @:ustruct extern class FMagicLeapARPinQuery {
  
  /**
    Indicate if the result set should be sorted by distance from TargetPoint. Sorting by istance will incur a performance penalty.
  **/
  @:uproperty public var bSorted : Bool;
  
  /**
    Return only entries within radius of the sphere from TargetPoint. Set to 0 for unbounded results. Filtering by distance will incur a performance penalty.
  **/
  @:uproperty public var Radius : unreal.Float32;
  
  /**
    Center query point from where the nearest neighbours will be calculated.
  **/
  @:uproperty public var TargetPoint : unreal.FVector;
  
  /**
    Upper bound number of expected results. The implementation may return less entries than requested. Set to -1 for all available.
  **/
  @:uproperty public var MaxResults : unreal.Int32;
  
  /**
    Types of Pins to look for
  **/
  @:uproperty public var Types : unreal.TSet<unreal.magicleaparpin.EMagicLeapARPinType>;
  
}
