/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.magicleaparpin;

/**
  Base class to save game data associated with a given pin. Inherit from this class and set it to be the PinDataClass in the MagicLeapARPinComponent to save and restore related data.
**/
@:umodule("MagicLeapARPin")
@:glueCppIncludes("MagicLeapARPinTypes.h")
@:uextern @:uclass extern class UMagicLeapARPinSaveGame extends unreal.USaveGame {
  @:uproperty public var bShouldPinActor : Bool;
  @:uproperty public var PinTransform : unreal.FTransform;
  @:uproperty public var ComponentWorldTransform : unreal.FTransform;
  @:uproperty public var PinnedID : unreal.FGuid;
  
}
