/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.livelinksequencer;

/**
  Abstract based for movie scene track recorders that can record LiveLink Controllers
**/
@:umodule("LiveLinkSequencer")
@:glueCppIncludes("MovieSceneLiveLinkControllerTrackRecorder.h")
@:uextern @:uclass extern class UMovieSceneLiveLinkControllerTrackRecorder extends unreal.taketrackrecorders.UMovieSceneTrackRecorder {
  
  /**
    The LiveLink controller that this track record will record properties from
  **/
  @:uproperty private var LiveLinkControllerToRecord : unreal.livelinkcomponents.ULiveLinkControllerBase;
  
}
