/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.augmentedreality;

/**
  Options for how environment textures are generated. This feature is used by ARKit.
**/
@:umodule("AugmentedReality")
@:glueCppIncludes("Public/ARSessionConfig.h")
@:uname("EAREnvironmentCaptureProbeType")
@:class @:uextern @:uenum extern enum EAREnvironmentCaptureProbeType {
  
  /**
    Disables environment texture generation.
  **/
  None;
  
  /**
    The app specifies where the environment capture probes are located and their size.
  **/
  Manual;
  
  /**
    The AR system automatically creates and places the environment capture probes.
  **/
  Automatic;
  
}
