/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.augmentedreality;

/**
  Options for the kind of data to update during Face Tracking. This feature is used by ARKit.
**/
@:umodule("AugmentedReality")
@:glueCppIncludes("Public/ARSessionConfig.h")
@:uname("EARFaceTrackingUpdate")
@:class @:uextern @:uenum extern enum EARFaceTrackingUpdate {
  
  /**
    Both curves and geometry are updated. This is useful for mesh visualization.
  **/
  CurvesAndGeo;
  
  /**
    Only the curve data is updated.
  **/
  CurvesOnly;
  
}
