/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.augmentedreality;

/**
  Options for how the scene should be reconstructed. This feature is used by ARKit.
**/
@:umodule("AugmentedReality")
@:glueCppIncludes("Public/ARSessionConfig.h")
@:uname("EARSceneReconstruction")
@:class @:uextern @:uenum extern enum EARSceneReconstruction {
  
  /**
    Disables scene reconstruction
  **/
  None;
  
  /**
    Creates a mesh approximation of the environment.
  **/
  MeshOnly;
  
  /**
    Creates a mesh approximation of the environment and classifies the objects constructed.
  **/
  MeshWithClassification;
  
}
