/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.augmentedreality;

/**
  Blueprint async task to check Geo tracking availability.
**/
@:umodule("AugmentedReality")
@:glueCppIncludes("ARGeoTrackingSupport.h")
@:uextern @:uclass extern class UCheckGeoTrackingAvailabilityAsyncTaskBlueprintProxy extends unreal.augmentedreality.UARBaseAsyncTaskBlueprintProxy {
  @:uproperty public var OnFailed : unreal.augmentedreality.FGeoTrackingAvailabilityDelegate;
  @:uproperty public var OnSuccess : unreal.augmentedreality.FGeoTrackingAvailabilityDelegate;
  
  /**
    Check Geo tracking availability at the user's current location.
  **/
  @:ufunction(BlueprintCallable) static public function CheckGeoTrackingAvailability(WorldContextObject : unreal.UObject) : unreal.augmentedreality.UCheckGeoTrackingAvailabilityAsyncTaskBlueprintProxy;
  
  /**
    Check Geo tracking availability at a specific Geo location.
  **/
  @:ufunction(BlueprintCallable) static public function CheckGeoTrackingAvailabilityAtLocation(WorldContextObject : unreal.UObject, Longitude : unreal.Float32, Latitude : unreal.Float32) : unreal.augmentedreality.UCheckGeoTrackingAvailabilityAsyncTaskBlueprintProxy;
  
}
