/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.slate;

/**
  Set behavior when user focus changes inside this scroll box
**/
@:umodule("Slate")
@:glueCppIncludes("Public/Widgets/Layout/SScrollBox.h")
@:uname("EScrollWhenFocusChanges")
@:class @:uextern @:uenum extern enum EScrollWhenFocusChanges {
  
  /**
    Don't automatically scroll, navigation or child widget will handle this
  **/
  NoScroll;
  
  /**
    Instantly scroll using NavigationDestination rule
  **/
  InstantScroll;
  
  /**
    Use animation to scroll using NavigationDestination rule
  **/
  AnimatedScroll;
  
}
