/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.imagewrapper;

/**
  Bitmap info header versions.
**/
@:umodule("ImageWrapper")
@:glueCppIncludes("Public/BmpImageSupport.h")
@:uname("EBitmapHeaderVersion")
@:class @:uextern @:uenum extern enum EBitmapHeaderVersion {
  BHV_BITMAPINFOHEADER;
  BHV_BITMAPV2INFOHEADER;
  BHV_BITMAPV3INFOHEADER;
  BHV_BITMAPV4HEADER;
  BHV_BITMAPV5HEADER;
  
}
