/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.chaoscloth;

@:umodule("ChaosCloth")
@:glueCppIncludes("ChaosCloth/ChaosClothingSimulationInteractor.h")
@:uextern @:uclass extern class UChaosClothingInteractor extends unreal.clothingsystemruntimeinterface.UClothingInteractor {
  @:ufunction(BlueprintCallable) @:final public function SetMaterialLinear(EdgeStiffness : unreal.Float32 = 1.000000, BendingStiffness : unreal.Float32 = 1.000000, AreaStiffness : unreal.Float32 = 1.000000) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetLongRangeAttachmentLinear(TetherStiffness : unreal.Float32 = 1.000000) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetLongRangeAttachment(@:opt("(X=0.000,Y=1.000)") TetherStiffness : unreal.FVector2D) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetCollision(CollisionThickness : unreal.Float32 = 1.000000, FrictionCoefficient : unreal.Float32 = 0.800000, bUseCCD : Bool = false, SelfCollisionThickness : unreal.Float32 = 2.000000) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetDamping(DampingCoefficient : unreal.Float32 = 0.010000) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetAerodynamics(DragCoefficient : unreal.Float32 = 0.070000, LiftCoefficient : unreal.Float32 = 0.035000, @:opt("0.000000,0.000000,0.000000") WindVelocity : unreal.FVector) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetGravity(GravityScale : unreal.Float32 = 1.000000, bIsGravityOverridden : Bool = false, @:opt("0.000000,0.000000,-981.000000") GravityOverride : unreal.FVector) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetAnimDriveLinear(AnimDriveStiffness : unreal.Float32 = 0.000000) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetAnimDrive(@:opt("(X=0.000,Y=1.000)") AnimDriveStiffness : unreal.FVector2D, @:opt("(X=0.000,Y=1.000)") AnimDriveDamping : unreal.FVector2D) : Void;
  @:ufunction(BlueprintCallable) @:final public function SetVelocityScale(@:opt("0.750000,0.750000,0.750000") LinearVelocityScale : unreal.FVector, AngularVelocityScale : unreal.Float32 = 0.750000, FictitiousAngularScale : unreal.Float32 = 1.000000) : Void;
  @:ufunction(BlueprintCallable) @:final public function ResetAndTeleport(bReset : Bool = false, bTeleport : Bool = false) : Void;
  
}
