/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.chaos;

@:umodule("Chaos")
@:glueCppIncludes("Public/Field/FieldSystemTypes.h")
@:uname("EWaveFunctionType")
@:uextern @:uenum extern enum EWaveFunctionType {
  
  /**
    Cosine wave that will move in time.
    @DisplayName Cosine
  **/
  @DisplayName("Cosine")
  Field_Wave_Cosine;
  
  /**
    Gaussian wave that will move in time.
    @DisplayName Gaussian
  **/
  @DisplayName("Gaussian")
  Field_Wave_Gaussian;
  
  /**
    The radial falloff radius will move along temporal wave.
    @DisplayName Falloff
  **/
  @DisplayName("Falloff")
  Field_Wave_Falloff;
  
  /**
    The magnitude of the field will decay in time.
    @DisplayName Decay
  **/
  @DisplayName("Decay")
  Field_Wave_Decay;
  
  /**
    //256th entry
  **/
  Field_Wave_Max;
  
}
