/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.headmounteddisplay;

/**
  Transforms that are tracked on the hand.
  Matches the enums from WMR to make it a direct mapping
**/
@:umodule("HeadMountedDisplay")
@:glueCppIncludes("Public/HeadMountedDisplayTypes.h")
@:uname("EHandKeypoint")
@:class @:uextern @:uenum extern enum EHandKeypoint {
  Palm;
  Wrist;
  ThumbMetacarpal;
  ThumbProximal;
  ThumbDistal;
  ThumbTip;
  IndexMetacarpal;
  IndexProximal;
  IndexIntermediate;
  IndexDistal;
  IndexTip;
  MiddleMetacarpal;
  MiddleProximal;
  MiddleIntermediate;
  MiddleDistal;
  MiddleTip;
  RingMetacarpal;
  RingProximal;
  RingIntermediate;
  RingDistal;
  RingTip;
  LittleMetacarpal;
  LittleProximal;
  LittleIntermediate;
  LittleDistal;
  LittleTip;
  
}
