/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.chaossolverengine;

@:umodule("ChaosSolverEngine")
@:glueCppIncludes("Chaos/ChaosSolverActor.h")
@:uextern @:uclass extern class AChaosSolverActor extends unreal.AActor {
  
  /**
    * Display icon in the editor
  **/
  @:uproperty public var SpriteComponent : unreal.UBillboardComponent;
  
  /**
    * Control to pause/step/substep the solver to the next synchronization point.
  **/
  @:uproperty public var ChaosDebugSubstepControl : unreal.chaossolverengine.FChaosDebugSubstepControl;
  @:uproperty public var FloorHeight : unreal.Float32;
  
  /**
    End deprecated properties
  **/
  @:uproperty public var bHasFloor : Bool;
  @:deprecated @:uproperty public var bGenerateContactGraph_DEPRECATED : Bool;
  @:deprecated @:uproperty public var MassScale_DEPRECATED : unreal.Float32;
  @:deprecated @:uproperty public var TrailingFilterSettings_DEPRECATED : unreal.chaos.FSolverTrailingFilterSettings;
  @:deprecated @:uproperty public var DoGenerateTrailingData_DEPRECATED : Bool;
  @:deprecated @:uproperty public var BreakingFilterSettings_DEPRECATED : unreal.chaos.FSolverBreakingFilterSettings;
  @:deprecated @:uproperty public var DoGenerateBreakingData_DEPRECATED : Bool;
  @:deprecated @:uproperty public var CollisionFilterSettings_DEPRECATED : unreal.chaos.FSolverCollisionFilterSettings;
  @:deprecated @:uproperty public var DoGenerateCollisionData_DEPRECATED : Bool;
  @:deprecated @:uproperty public var ClusterUnionConnectionType_DEPRECATED : unreal.chaossolverengine.EClusterConnectionTypeEnum;
  @:deprecated @:uproperty public var ClusterConnectionFactor_DEPRECATED : unreal.Float32;
  @:deprecated @:uproperty public var PushOutPairIterations_DEPRECATED : unreal.Int32;
  @:deprecated @:uproperty public var PushOutIterations_DEPRECATED : unreal.Int32;
  @:deprecated @:uproperty public var CollisionIterations_DEPRECATED : unreal.Int32;
  
  /**
    Deprecated solver properties (moved to FChaosSolverConfiguration)
  **/
  @:deprecated @:uproperty public var TimeStepMultiplier_DEPRECATED : unreal.Float32;
  @:uproperty public var Properties : unreal.chaos.FChaosSolverConfiguration;
  
  /**
    Makes this solver the current world solver. Dynamically spawned objects will have their physics state created in this solver.
  **/
  @:ufunction(BlueprintCallable) @:final public function SetAsCurrentWorldSolver() : Void;
  
  /**
    Controls whether the solver is able to simulate particles it controls
  **/
  @:ufunction(BlueprintCallable) public function SetSolverActive(bActive : Bool) : Void;
  
}
