/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.chaossolverengine;

/**
  Settings class for the Chaos Solver
**/
@:umodule("ChaosSolverEngine")
@:glueCppIncludes("Chaos/ChaosSolverSettings.h")
@:uextern @:uclass extern class UChaosSolverSettings extends unreal.developersettings.UDeveloperSettings {
  
  /**
    The class to use when auto-creating a default chaos solver actor
  **/
  @:uproperty public var DefaultChaosSolverActorClass : unreal.FSoftClassPath;
  
}
