/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.templatesequence;

/**
  WARNING: This type was not defined as DLL export on its declaration. Because of that, some of its methods are inaccessible
  
  A dummy class that we give to a sequence in lieu of an actual camera actor.
**/
@:umodule("TemplateSequence")
@:glueCppIncludes("SequenceCameraShake.h")
@:noClass @:uextern @:uclass extern class USequenceCameraShakeCameraStandIn extends unreal.UObject implements unreal.moviescene.IMovieSceneSceneComponentImpersonator {
  @:uproperty public var CurrentFocusDistance : unreal.Float32;
  @:uproperty public var CurrentAperture : unreal.Float32;
  @:uproperty public var CurrentFocalLength : unreal.Float32;
  @:uproperty public var FocusSettings : unreal.cinematiccamera.FCameraFocusSettings;
  @:uproperty public var LensSettings : unreal.cinematiccamera.FCameraLensSettings;
  
  /**
    Cine camera component properties
  **/
  @:uproperty public var Filmback : unreal.cinematiccamera.FCameraFilmbackSettings;
  @:uproperty public var PostProcessBlendWeight : unreal.Float32;
  @:uproperty public var PostProcessSettings : unreal.FPostProcessSettings;
  @:uproperty public var AspectRatio : unreal.Float32;
  @:uproperty public var bConstrainAspectRatio : Bool;
  
  /**
    Camera component properties
  **/
  @:uproperty public var FieldOfView : unreal.Float32;
  // MovieSceneSceneComponentImpersonator interface implementation
  
}
