/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.oculusinput;

/**
  EBone is enum representing the Bone Ids that come from the Oculus Runtime.
**/
@:umodule("OculusInput")
@:glueCppIncludes("Public/OculusInputFunctionLibrary.h")
@:uname("EBone")
@:class @:uextern @:uenum extern enum EBone {
  
  /**
    Wrist Root
  **/
  @DisplayName("Wrist Root")
  Wrist_Root;
  
  /**
    Hand Start
  **/
  @DisplayName("Hand Start")
  Hand_Start;
  
  /**
    Forearm Stub
  **/
  @DisplayName("Forearm Stub")
  Forearm_Stub;
  
  /**
    Thumb0
  **/
  @DisplayName("Thumb0")
  Thumb_0;
  
  /**
    Thumb1
  **/
  @DisplayName("Thumb1")
  Thumb_1;
  
  /**
    Thumb2
  **/
  @DisplayName("Thumb2")
  Thumb_2;
  
  /**
    Thumb3
  **/
  @DisplayName("Thumb3")
  Thumb_3;
  
  /**
    Index1
  **/
  @DisplayName("Index1")
  Index_1;
  
  /**
    Index2
  **/
  @DisplayName("Index2")
  Index_2;
  
  /**
    Index3
  **/
  @DisplayName("Index3")
  Index_3;
  
  /**
    Middle1
  **/
  @DisplayName("Middle1")
  Middle_1;
  
  /**
    Middle2
  **/
  @DisplayName("Middle2")
  Middle_2;
  
  /**
    Middle3
  **/
  @DisplayName("Middle3")
  Middle_3;
  
  /**
    Ring1
  **/
  @DisplayName("Ring1")
  Ring_1;
  
  /**
    Ring2
  **/
  @DisplayName("Ring2")
  Ring_2;
  
  /**
    Ring3
  **/
  @DisplayName("Ring3")
  Ring_3;
  
  /**
    Pinky0
  **/
  @DisplayName("Pinky0")
  Pinky_0;
  
  /**
    Pinky1
  **/
  @DisplayName("Pinky1")
  Pinky_1;
  
  /**
    Pinky2
  **/
  @DisplayName("Pinky2")
  Pinky_2;
  
  /**
    Pinky3
  **/
  @DisplayName("Pinky3")
  Pinky_3;
  
  /**
    Thumb Tip
  **/
  @DisplayName("Thumb Tip")
  Thumb_Tip;
  
  /**
    Max Skinnable
  **/
  @DisplayName("Max Skinnable")
  Max_Skinnable;
  
  /**
    Index Tip
  **/
  @DisplayName("Index Tip")
  Index_Tip;
  
  /**
    Middle Tip
  **/
  @DisplayName("Middle Tip")
  Middle_Tip;
  
  /**
    Ring Tip
  **/
  @DisplayName("Ring Tip")
  Ring_Tip;
  
  /**
    Pinky Tip
  **/
  @DisplayName("Pinky Tip")
  Pinky_Tip;
  
  /**
    Hand End
  **/
  @DisplayName("Hand End")
  Hand_End;
  
  /**
    Hand Max
  **/
  @DisplayName("Hand Max")
  Bone_Max;
  
  /**
    Invalid
  **/
  @DisplayName("Invalid")
  Invalid;
  
}
