/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.udpmessaging;

/**
  Defines the UDP message format available (how the message data is encoded).
**/
@:umodule("UdpMessaging")
@:glueCppIncludes("Public/Shared/UdpMessagingSettings.h")
@:uname("EUdpMessageFormat")
@:class @:uextern @:uenum extern enum EUdpMessageFormat {
  
  /**
    No format specified. Legacy - Not exposed to user.
  **/
  None;
  
  /**
    JSON format specified. Legacy - Not exposed to user.
  **/
  Json;
  
  /**
    Tagged property format specified. Legacy - Not exposed to user.
  **/
  TaggedProperty;
  
  /**
    UDP messages are encoded in CBOR, using the platform endianness. This is the fastest and preferred option, but the CBOR data will not be readable by an external standard-compliant CBOR parser
    if generated from a little endian platform. If the data needs to be consumed outside the Unreal Engine, consider using CborStandardEndianness format instead.
    @DisplayName CBOR (Platform Endianness)
  **/
  @DisplayName("CBOR (Platform Endianness)")
  CborPlatformEndianness;
  
  /**
    UDP messages are encoded in CBOR, using the CBOR standard-complinant endianness (big endian). It will perform slower on a little-endian platform, but the data will be readable by standard CBOR parsers.
    Useful if the UDP messages needs to be analyzed/consumed outside the Unreal Engine.
    @DisplayName CBOR (Standard Endianness)
  **/
  @DisplayName("CBOR (Standard Endianness)")
  CborStandardEndianness;
  
}
