/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.augmentedreality;

@:umodule("AugmentedReality")
@:glueCppIncludes("Public/ARGeoTrackingSupport.h")
@:uname("EARGeoTrackingStateReason")
@:class @:uextern @:uenum extern enum EARGeoTrackingStateReason {
  
  /**
    No issues reported.
  **/
  None;
  
  /**
    Geo tracking is not available at the location.
  **/
  NotAvailableAtLocation;
  
  /**
    Geo tracking needs location permissions from the user.
  **/
  NeedLocationPermissions;
  
  /**
    The user is pointing the device too low to use geo tracking.
  **/
  DevicePointedTooLow;
  
  /**
    The session is unsure of the device’s pose in the physical environment.
  **/
  WorldTrackingUnstable;
  
  /**
    The framework is waiting for a position for the user.
  **/
  WaitingForLocation;
  
  /**
    The framework is actively attempting to download localization imagery.
  **/
  GeoDataNotLoaded;
  
  /**
    The framework failed to match its localization imagery with the device’s camera captures.
  **/
  VisualLocalizationFailed;
  
  /**
    The framework is waiting for the availability check.
  **/
  WaitingForAvailabilityCheck;
  
}
