/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.augmentedreality;

/**
  Called just before the AR actor is destroyed on the server
  @param Actor
  
**/
@:glueCppIncludes("Public/ARLifeCycleComponent.h")
@:uParamName("Actor")
@:umodule("AugmentedReality")
@:uname("UARLifeCycleComponent.FInstanceARActorToBeDestroyedDelegate")
typedef FInstanceARActorToBeDestroyedDelegate = unreal.DynamicMulticastDelegate<FInstanceARActorToBeDestroyedDelegate, unreal.augmentedreality.AARActor->Void>;