/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.geometrycollectionengine;

/**
  A collision event data structure
**/
@:umodule("GeometryCollectionEngine")
@:glueCppIncludes("Public/ChaosCollisionEventFilter.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FChaosCollisionEventData {
  
  /**
    The accumulated impulse vector of the collision event
  **/
  @:uproperty public var Impulse : unreal.FVector;
  
  /**
    The mass of object 2 of the collision event
  **/
  @:uproperty public var Mass2 : unreal.Float32;
  
  /**
    The mass of object 1 of the collision event
  **/
  @:uproperty public var Mass1 : unreal.Float32;
  
  /**
    The velocity of object 2 of the collision event
  **/
  @:uproperty public var Velocity2 : unreal.FVector;
  
  /**
    The velocity of object 1 of the collision event
  **/
  @:uproperty public var Velocity1 : unreal.FVector;
  
  /**
    Normal of the collision event
  **/
  @:uproperty public var Normal : unreal.FVector;
  
  /**
    Location of the collision event
  **/
  @:uproperty public var Location : unreal.FVector;
  
}
