/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.onlinesubsystemutils;

/**
  State of a purchase transaction
**/
@:umodule("OnlineSubsystemUtils")
@:glueCppIncludes("Classes/InAppPurchaseCallbackProxy2.h")
@:uname("EInAppPurchaseStatus")
@:class @:uextern @:uenum extern enum EInAppPurchaseStatus {
  
  /**
    Invalid
  **/
  @DisplayName("Invalid")
  Invalid;
  
  /**
    purchase completed but failed
    @DisplayName Failed
  **/
  @DisplayName("Failed")
  Failed;
  
  /**
    purchase has been deferred (neither failed nor completed)
    @DisplayName Deferred
  **/
  @DisplayName("Deferred")
  Deferred;
  
  /**
    purchase canceled by user
    @DisplayName Canceled
  **/
  @DisplayName("Canceled")
  Canceled;
  
  /**
    purchase succeeded
    @DisplayName Purchased
  **/
  @DisplayName("Purchased")
  Purchased;
  
  /**
    restore succeeded
    @DisplayName Restored
  **/
  @DisplayName("Restored")
  Restored;
  
}
