/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.screenshotcomparisontools;

@:umodule("ScreenShotComparisonTools")
@:glueCppIncludes("ScreenShotComparisonSettings.h")
@:uextern @:uclass extern class UScreenShotComparisonSettings extends unreal.UObject {
  
  /**
    An array of entries that describe other platforms we can use for fallbacks when comparing screenshots
  **/
  @:uproperty public var ScreenshotFallbackPlatforms : unreal.TArray<unreal.screenshotcomparisontools.FScreenshotFallbackEntry>;
  
  /**
    if true, any checked-in test results for confidential platforms will be put under <ProjectDir>/Platforms/<Platform>/Test instead of <ProjectDir>/Test
  **/
  @:uproperty public var bUseConfidentialPlatformPathsForSavedResults : Bool;
  
}
