/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.chaosniagara;

@:umodule("ChaosNiagara")
@:glueCppIncludes("Classes/NiagaraDataInterfaceChaosDestruction.h")
@:uname("ELocationFilteringModeEnum")
@:class @:uextern @:uenum extern enum ELocationFilteringModeEnum {
  
  /**
    Inclusive
  **/
  @DisplayName("Inclusive")
  ChaosNiagara_LocationFilteringMode_Inclusive;
  
  /**
    Exclusive
  **/
  @DisplayName("Exclusive")
  ChaosNiagara_LocationFilteringMode_Exclusive;
  
  /**
    256th entry
  **/
  ChaosNiagara_Max;
  
}
