/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.landscape;

@:umodule("Landscape")
@:glueCppIncludes("Classes/Landscape.h")
@:uname("EWeightmapRTType")
@:class @:uextern @:uenum extern enum EWeightmapRTType {
  WeightmapRT_Scratch_RGBA;
  WeightmapRT_Scratch1;
  WeightmapRT_Scratch2;
  WeightmapRT_Scratch3;
  
  /**
    Mips RT
  **/
  WeightmapRT_Mip0;
  WeightmapRT_Mip1;
  WeightmapRT_Mip2;
  WeightmapRT_Mip3;
  WeightmapRT_Mip4;
  WeightmapRT_Mip5;
  WeightmapRT_Mip6;
  WeightmapRT_Mip7;
  WeightmapRT_Count;
  
}
