/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

@:umodule("MovieScene")
@:glueCppIncludes("Public/Evaluation/MovieSceneEvaluationField.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMovieSceneFieldEntry_ChildTemplate {
  @:uproperty public var ForcedTime : unreal.FFrameNumber;
  @:uproperty public var Flags : unreal.moviescene.ESectionEvaluationFlags;
  @:uproperty public var ChildIndex : unreal.UInt16;
  
}
