/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

/**
  POD struct that represents a number of loops where -1 signifies infinite looping, 0 means no loops, etc
  Defined as a struct rather than an int so a property type customization can be bound to it
**/
@:umodule("MovieScene")
@:glueCppIncludes("Public/MovieSceneSequencePlayer.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMovieSceneSequenceLoopCount {
  
  /**
    Whether or not to loop playback. If Loop Exactly is chosen, you can specify the number of times to loop
  **/
  @:uproperty public var Value : unreal.Int32;
  
}
