/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

@:umodule("MovieScene")
@:glueCppIncludes("Evaluation/IMovieSceneCustomClockSource.h")
@:uextern @:uclass extern interface IMovieSceneCustomClockSource {
  @:ufunction public function OnTick(DeltaSeconds : unreal.Float32, InPlayRate : unreal.Float32) : Void;
  @:ufunction public function OnStartPlaying(InStartTime : unreal.Const<unreal.PRef<unreal.FQualifiedFrameTime>>) : Void;
  @:ufunction public function OnStopPlaying(InStopTime : unreal.Const<unreal.PRef<unreal.FQualifiedFrameTime>>) : Void;
  @:ufunction public function OnRequestCurrentTime(InCurrentTime : unreal.Const<unreal.PRef<unreal.FQualifiedFrameTime>>, InPlayRate : unreal.Float32) : unreal.FFrameTime;
  
}
