/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.niagaraeditor;

@:umodule("NiagaraEditor")
@:glueCppIncludes("NiagaraClipboard.h")
@:uextern @:uclass extern class UNiagaraClipboardEditorScriptingUtilities extends unreal.UObject {
  @:ufunction(BlueprintCallable) static public function TryGetLocalValueAsFloat(InInput : unreal.Const<unreal.niagaraeditor.UNiagaraClipboardFunctionInput>, bOutSucceeded : Bool, OutValue : unreal.Float32) : Void;
  @:ufunction(BlueprintCallable) static public function TryGetLocalValueAsInt(InInput : unreal.Const<unreal.niagaraeditor.UNiagaraClipboardFunctionInput>, bOutSucceeded : Bool, OutValue : unreal.Int32) : Void;
  @:ufunction(BlueprintCallable) static public function TrySetLocalValueAsInt(InInput : unreal.niagaraeditor.UNiagaraClipboardFunctionInput, bOutSucceeded : Bool, InValue : unreal.Int32, bLooseTyping : Bool = true) : Void;
  @:ufunction(BlueprintCallable) static public function GetTypeName(InInput : unreal.Const<unreal.niagaraeditor.UNiagaraClipboardFunctionInput>) : unreal.FName;
  @:ufunction(BlueprintCallable) static public function CreateFloatLocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InLocalValue : unreal.Float32) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateVec2LocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InVec2Value : unreal.FVector2D) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateVec3LocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InVec3Value : unreal.FVector) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateIntLocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InLocalValue : unreal.Int32) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateBoolLocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InBoolValue : Bool) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateStructLocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InStructValue : unreal.UUserDefinedStruct) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateEnumLocalValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditCoditionValue : Bool, InEnumType : unreal.UUserDefinedEnum, InEnumValue : unreal.Int32) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateLinkedValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, InInputTypeName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InLinkedValue : unreal.FName) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateDataValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InDataValue : unreal.niagara.UNiagaraDataInterface) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateExpressionValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, InInputTypeName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InExpressionValue : unreal.FString) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  @:ufunction(BlueprintCallable) static public function CreateDynamicValueInput(InOuter : unreal.UObject, InInputName : unreal.FName, InInputTypeName : unreal.FName, bInHasEditCondition : Bool, bInEditConditionValue : Bool, InDynamicValueName : unreal.FString, InDynamicValue : unreal.niagara.UNiagaraScript) : unreal.niagaraeditor.UNiagaraClipboardFunctionInput;
  
}
